// Auto-generated by scripts/generate-game-data.mjs
// Do not edit manually. Run: npm run generate:game-data
// Generated at: 2026-07-14T18:17:40.122Z
// Game data version: 79323581daae3bb1
// Static data version: a9a9d3105392ff90
// Source bundle: https://stonegy-online.com/_next/static/chunks/pages/_app-f431d076605ee183.js

export const BATTLE_OPTIONS = {
  "heals": [
    {
      "name": "Small Health Potion",
      "levelMin": 0,
      "vocation": [
        "DRUID",
        "KNIGHT",
        "PALADIN",
        "SORCERER"
      ]
    },
    {
      "name": "Health Potion",
      "levelMin": 0,
      "vocation": [
        "DRUID",
        "KNIGHT",
        "PALADIN",
        "SORCERER"
      ]
    },
    {
      "name": "Strong Health Potion",
      "levelMin": 50,
      "vocation": [
        "KNIGHT",
        "PALADIN"
      ]
    },
    {
      "name": "Great Health Potion",
      "levelMin": 80,
      "vocation": [
        "KNIGHT"
      ]
    },
    {
      "name": "Great Spirit Potion",
      "levelMin": 80,
      "vocation": [
        "PALADIN"
      ]
    },
    {
      "name": "Ultimate Health Potion",
      "levelMin": 130,
      "vocation": [
        "KNIGHT"
      ]
    },
    {
      "name": "Ultimate Spirit Potion",
      "levelMin": 130,
      "vocation": [
        "PALADIN"
      ]
    },
    {
      "name": "Supreme Health Potion",
      "levelMin": 200,
      "vocation": [
        "KNIGHT"
      ]
    },
    {
      "name": "Light Healing",
      "levelMin": 8,
      "vocation": [
        "DRUID",
        "SORCERER",
        "PALADIN"
      ]
    },
    {
      "name": "Intense Healing",
      "levelMin": 20,
      "vocation": [
        "DRUID",
        "SORCERER",
        "PALADIN"
      ]
    },
    {
      "name": "Ultimate Healing",
      "levelMin": 30,
      "vocation": [
        "DRUID",
        "SORCERER"
      ]
    },
    {
      "name": "Mass Healing",
      "levelMin": 36,
      "vocation": [
        "DRUID"
      ]
    },
    {
      "name": "Heal Friend",
      "levelMin": 18,
      "vocation": [
        "DRUID"
      ]
    },
    {
      "name": "Nature's Embrace",
      "levelMin": 300,
      "vocation": [
        "DRUID"
      ]
    },
    {
      "name": "Divine Healing",
      "levelMin": 35,
      "vocation": [
        "PALADIN"
      ]
    },
    {
      "name": "Salvation",
      "levelMin": 60,
      "vocation": [
        "PALADIN"
      ]
    },
    {
      "name": "Wound Cleansing",
      "levelMin": 8,
      "vocation": [
        "KNIGHT"
      ]
    },
    {
      "name": "Intense Wound Cleansing",
      "levelMin": 80,
      "vocation": [
        "KNIGHT"
      ]
    },
    {
      "name": "Fair Wound Cleansing",
      "levelMin": 300,
      "vocation": [
        "KNIGHT"
      ]
    }
  ],
  "manaPotions": [
    {
      "name": "Mana Potion",
      "levelMin": 0,
      "vocation": [
        "DRUID",
        "KNIGHT",
        "PALADIN",
        "SORCERER"
      ]
    },
    {
      "name": "Strong Mana Potion",
      "levelMin": 50,
      "vocation": [
        "DRUID",
        "KNIGHT",
        "PALADIN",
        "SORCERER"
      ]
    },
    {
      "name": "Great Mana Potion",
      "levelMin": 80,
      "vocation": [
        "PALADIN",
        "DRUID",
        "SORCERER"
      ]
    },
    {
      "name": "Ultimate Mana Potion",
      "levelMin": 130,
      "vocation": [
        "SORCERER",
        "DRUID"
      ]
    }
  ],
  "arrows": [
    {
      "name": "Simple Arrow",
      "levelMin": 0,
      "ammoKind": "ARROW"
    },
    {
      "name": "Arrow",
      "levelMin": 1,
      "ammoKind": "ARROW"
    },
    {
      "name": "Burst Arrow",
      "levelMin": 1,
      "ammoKind": "ARROW"
    },
    {
      "name": "Sniper Arrow",
      "levelMin": 20,
      "ammoKind": "ARROW"
    },
    {
      "name": "Earth Arrow",
      "levelMin": 20,
      "ammoKind": "ARROW"
    },
    {
      "name": "Flaming Arrow",
      "levelMin": 20,
      "ammoKind": "ARROW"
    },
    {
      "name": "Flash Arrow",
      "levelMin": 20,
      "ammoKind": "ARROW"
    },
    {
      "name": "Shiver Arrow",
      "levelMin": 20,
      "ammoKind": "ARROW"
    },
    {
      "name": "Tarsal Arrow",
      "levelMin": 30,
      "ammoKind": "ARROW"
    },
    {
      "name": "Onyx Arrow",
      "levelMin": 40,
      "ammoKind": "ARROW"
    },
    {
      "name": "Shatterstorm Arrow",
      "levelMin": 50,
      "ammoKind": "ARROW"
    },
    {
      "name": "Envenomed Arrow",
      "levelMin": 70,
      "ammoKind": "ARROW"
    },
    {
      "name": "Crystalline Arrow",
      "levelMin": 90,
      "ammoKind": "ARROW"
    },
    {
      "name": "Diamond Arrow",
      "levelMin": 150,
      "ammoKind": "ARROW"
    }
  ],
  "bolts": [
    {
      "name": "Bolt",
      "levelMin": 0,
      "ammoKind": "BOLT"
    },
    {
      "name": "Piercing Bolt",
      "levelMin": 30,
      "ammoKind": "BOLT"
    },
    {
      "name": "Vortex Bolt",
      "levelMin": 40,
      "ammoKind": "BOLT"
    },
    {
      "name": "Power Bolt",
      "levelMin": 55,
      "ammoKind": "BOLT"
    },
    {
      "name": "Drill Bolt",
      "levelMin": 70,
      "ammoKind": "BOLT"
    },
    {
      "name": "Prismatic Bolt",
      "levelMin": 90,
      "ammoKind": "BOLT"
    },
    {
      "name": "Spectral Bolt",
      "levelMin": 150,
      "ammoKind": "BOLT"
    }
  ],
  "spells": [
    {
      "name": "Buzz",
      "vocation": "SORCERER",
      "minLevel": 1,
      "minMagicLevel": 0,
      "category": "ATTACK"
    },
    {
      "name": "Lesser Ethereal Spear",
      "vocation": "PALADIN",
      "minLevel": 1,
      "minMagicLevel": 0,
      "category": "ATTACK"
    },
    {
      "name": "Lesser Front Sweep",
      "vocation": "KNIGHT",
      "minLevel": 1,
      "minMagicLevel": 0,
      "category": "ATTACK"
    },
    {
      "name": "Mud Attack",
      "vocation": "DRUID",
      "minLevel": 1,
      "minMagicLevel": 0,
      "category": "ATTACK"
    },
    {
      "name": "Magic Shield",
      "vocation": "SORCERER",
      "minLevel": 14,
      "minMagicLevel": 0,
      "category": "SUPPORT"
    },
    {
      "name": "Brutal Strike",
      "vocation": "KNIGHT",
      "minLevel": 16,
      "minMagicLevel": 0,
      "category": "ATTACK"
    },
    {
      "name": "Ethereal Spear",
      "vocation": "PALADIN",
      "minLevel": 23,
      "minMagicLevel": 0,
      "category": "ATTACK"
    },
    {
      "name": "Stone Shower Rune",
      "vocation": "DRUID",
      "minLevel": 28,
      "minMagicLevel": 4,
      "category": "ATTACK"
    },
    {
      "name": "Thunderstorm Rune",
      "vocation": "DRUID",
      "minLevel": 28,
      "minMagicLevel": 4,
      "category": "ATTACK"
    },
    {
      "name": "Whirlwind Throw",
      "vocation": "KNIGHT",
      "minLevel": 28,
      "minMagicLevel": 0,
      "category": "ATTACK"
    },
    {
      "name": "Great Energy Beam",
      "vocation": "SORCERER",
      "minLevel": 29,
      "minMagicLevel": 0,
      "category": "ATTACK"
    },
    {
      "name": "Avalanche Rune",
      "vocation": "DRUID",
      "minLevel": 30,
      "minMagicLevel": 4,
      "category": "ATTACK"
    },
    {
      "name": "Great Fireball Rune",
      "vocation": "DRUID",
      "minLevel": 30,
      "minMagicLevel": 4,
      "category": "ATTACK"
    },
    {
      "name": "Groundshaker",
      "vocation": "KNIGHT",
      "minLevel": 33,
      "minMagicLevel": 0,
      "category": "ATTACK"
    },
    {
      "name": "Berserk",
      "vocation": "KNIGHT",
      "minLevel": 35,
      "minMagicLevel": 0,
      "category": "ATTACK"
    },
    {
      "name": "Energy Wave",
      "vocation": "SORCERER",
      "minLevel": 38,
      "minMagicLevel": 0,
      "category": "ATTACK"
    },
    {
      "name": "Great Fire Wave",
      "vocation": "SORCERER",
      "minLevel": 38,
      "minMagicLevel": 0,
      "category": "ATTACK"
    },
    {
      "name": "Terra Wave",
      "vocation": "DRUID",
      "minLevel": 38,
      "minMagicLevel": 0,
      "category": "ATTACK"
    },
    {
      "name": "Divine Missile",
      "vocation": "PALADIN",
      "minLevel": 40,
      "minMagicLevel": 0,
      "category": "ATTACK"
    },
    {
      "name": "Strong Ice Wave",
      "vocation": "DRUID",
      "minLevel": 40,
      "minMagicLevel": 0,
      "category": "ATTACK"
    },
    {
      "name": "Sudden Death Rune",
      "vocation": "DRUID",
      "minLevel": 45,
      "minMagicLevel": 15,
      "category": "ATTACK"
    },
    {
      "name": "Divine Caldera",
      "vocation": "PALADIN",
      "minLevel": 50,
      "minMagicLevel": 0,
      "category": "ATTACK"
    },
    {
      "name": "Rage of the Skies",
      "vocation": "SORCERER",
      "minLevel": 55,
      "minMagicLevel": 0,
      "category": "ATTACK"
    },
    {
      "name": "Utamo Tempo",
      "vocation": "KNIGHT",
      "minLevel": 55,
      "minMagicLevel": 0,
      "category": "SUPPORT"
    },
    {
      "name": "Wrath of Nature",
      "vocation": "DRUID",
      "minLevel": 55,
      "minMagicLevel": 0,
      "category": "ATTACK"
    },
    {
      "name": "Sharpshooter",
      "vocation": "PALADIN",
      "minLevel": 60,
      "minMagicLevel": 0,
      "category": "SUPPORT"
    },
    {
      "name": "Utito Tempo",
      "vocation": "KNIGHT",
      "minLevel": 60,
      "minMagicLevel": 0,
      "category": "SUPPORT"
    },
    {
      "name": "Front Sweep",
      "vocation": "KNIGHT",
      "minLevel": 70,
      "minMagicLevel": 0,
      "category": "ATTACK"
    },
    {
      "name": "Strong Flame Strike",
      "vocation": "SORCERER",
      "minLevel": 70,
      "minMagicLevel": 0,
      "category": "ATTACK"
    },
    {
      "name": "Strong Terra Strike",
      "vocation": "DRUID",
      "minLevel": 70,
      "minMagicLevel": 0,
      "category": "ATTACK"
    },
    {
      "name": "Fierce Berserk",
      "vocation": "KNIGHT",
      "minLevel": 90,
      "minMagicLevel": 0,
      "category": "ATTACK"
    },
    {
      "name": "Strong Ethereal Spear",
      "vocation": "PALADIN",
      "minLevel": 90,
      "minMagicLevel": 0,
      "category": "ATTACK"
    },
    {
      "name": "Ultimate Flame Strike",
      "vocation": "SORCERER",
      "minLevel": 90,
      "minMagicLevel": 0,
      "category": "ATTACK"
    },
    {
      "name": "Ultimate Terra Strike",
      "vocation": "DRUID",
      "minLevel": 90,
      "minMagicLevel": 0,
      "category": "ATTACK"
    },
    {
      "name": "Ultimate Energy Strike",
      "vocation": "SORCERER",
      "minLevel": 100,
      "minMagicLevel": 0,
      "category": "ATTACK"
    },
    {
      "name": "Ultimate Ice Strike",
      "vocation": "DRUID",
      "minLevel": 100,
      "minMagicLevel": 0,
      "category": "ATTACK"
    },
    {
      "name": "Annihilation",
      "vocation": "KNIGHT",
      "minLevel": 110,
      "minMagicLevel": 0,
      "category": "ATTACK"
    },
    {
      "name": "Chivalrous Challenge",
      "vocation": "KNIGHT",
      "minLevel": 150,
      "minMagicLevel": 0,
      "category": "SUPPORT"
    },
    {
      "name": "Divine Dazzle",
      "vocation": "PALADIN",
      "minLevel": 250,
      "minMagicLevel": 0,
      "category": "SUPPORT"
    },
    {
      "name": "Expose Weakness",
      "vocation": "SORCERER",
      "minLevel": 275,
      "minMagicLevel": 0,
      "category": "SUPPORT"
    },
    {
      "name": "Sap Strength",
      "vocation": "SORCERER",
      "minLevel": 275,
      "minMagicLevel": 0,
      "category": "SUPPORT"
    }
  ]
};
