// Auto-generated by scripts/generate-game-data.mjs
// Do not edit manually. Run: npm run generate:game-data
// Generated at: 2026-07-15T03:03:27.609Z
// Source: stonegy app bundle (bosses Map)

export const BOSSES = [
  {
    "id": 1,
    "monsterId": 12,
    "rarity": 30,
    "bossType": "Archfoe",
    "recommendedLevel": 80
  },
  {
    "id": 2,
    "monsterId": 23,
    "rarity": 30,
    "bossType": "Archfoe",
    "recommendedLevel": 80
  },
  {
    "id": 3,
    "monsterId": 24,
    "rarity": 5,
    "bossType": "Nemesis",
    "recommendedLevel": 40
  },
  {
    "id": 4,
    "monsterId": 25,
    "rarity": 5,
    "bossType": "Nemesis",
    "recommendedLevel": 40
  },
  {
    "id": 5,
    "monsterId": 43,
    "rarity": 30,
    "bossType": "Archfoe",
    "recommendedLevel": 150
  },
  {
    "id": 6,
    "monsterId": 71,
    "rarity": 30,
    "bossType": "Archfoe",
    "recommendedLevel": 200
  },
  {
    "id": 7,
    "monsterId": 72,
    "rarity": 30,
    "bossType": "Archfoe",
    "recommendedLevel": 150
  },
  {
    "id": 8,
    "monsterId": 93,
    "rarity": 30,
    "bossType": "Archfoe",
    "recommendedLevel": 300
  },
  {
    "id": 10,
    "monsterId": 98,
    "rarity": 30,
    "bossType": "Archfoe",
    "recommendedLevel": 400
  },
  {
    "id": 11,
    "monsterId": 99,
    "rarity": 100,
    "bossType": "Bane",
    "recommendedLevel": 300
  },
  {
    "id": 12,
    "monsterId": 100,
    "rarity": 30,
    "bossType": "Archfoe",
    "recommendedLevel": 300
  },
  {
    "id": 13,
    "monsterId": 102,
    "rarity": 30,
    "bossType": "Archfoe",
    "recommendedLevel": 300
  },
  {
    "id": 14,
    "monsterId": 103,
    "rarity": 30,
    "bossType": "Archfoe",
    "recommendedLevel": 400
  },
  {
    "id": 15,
    "monsterId": 104,
    "rarity": 5,
    "bossType": "Nemesis",
    "recommendedLevel": 400
  },
  {
    "id": 16,
    "monsterId": 105,
    "rarity": 30,
    "bossType": "Archfoe",
    "recommendedLevel": 300
  },
  {
    "id": 17,
    "monsterId": 106,
    "rarity": 100,
    "bossType": "Bane",
    "recommendedLevel": 220
  },
  {
    "id": 18,
    "monsterId": 107,
    "rarity": 5,
    "bossType": "Nemesis",
    "recommendedLevel": 600
  },
  {
    "id": 19,
    "monsterId": 252,
    "rarity": 100,
    "bossType": "Bane",
    "recommendedLevel": 80
  },
  {
    "id": 20,
    "monsterId": 253,
    "rarity": 100,
    "bossType": "Bane",
    "recommendedLevel": 260
  },
  {
    "id": 21,
    "monsterId": 255,
    "rarity": 100,
    "bossType": "Bane",
    "recommendedLevel": 250
  },
  {
    "id": 22,
    "monsterId": 256,
    "rarity": 100,
    "bossType": "Bane",
    "recommendedLevel": 300
  },
  {
    "id": 23,
    "monsterId": 257,
    "rarity": 100,
    "bossType": "Bane",
    "recommendedLevel": 150
  },
  {
    "id": 24,
    "monsterId": 258,
    "rarity": 30,
    "bossType": "Archfoe",
    "recommendedLevel": 150
  },
  {
    "id": 25,
    "monsterId": 259,
    "rarity": 30,
    "bossType": "Archfoe",
    "recommendedLevel": 200
  },
  {
    "id": 26,
    "monsterId": 260,
    "rarity": 5,
    "bossType": "Nemesis",
    "recommendedLevel": 400
  },
  {
    "id": 27,
    "monsterId": 262,
    "rarity": 30,
    "bossType": "Archfoe",
    "recommendedLevel": 250
  },
  {
    "id": 28,
    "monsterId": 263,
    "rarity": 30,
    "bossType": "Archfoe",
    "recommendedLevel": 350
  },
  {
    "id": 29,
    "monsterId": 264,
    "rarity": 30,
    "bossType": "Archfoe",
    "recommendedLevel": 200
  },
  {
    "id": 30,
    "monsterId": 265,
    "rarity": 30,
    "bossType": "Archfoe",
    "recommendedLevel": 250
  },
  {
    "id": 31,
    "monsterId": 267,
    "rarity": 100,
    "bossType": "Bane",
    "recommendedLevel": 300
  },
  {
    "id": 32,
    "monsterId": 268,
    "rarity": 100,
    "bossType": "Bane",
    "recommendedLevel": 300
  },
  {
    "id": 33,
    "monsterId": 269,
    "rarity": 100,
    "bossType": "Bane",
    "recommendedLevel": 300
  },
  {
    "id": 34,
    "monsterId": 270,
    "rarity": 100,
    "bossType": "Bane",
    "recommendedLevel": 200
  },
  {
    "id": 35,
    "monsterId": 271,
    "rarity": 100,
    "bossType": "Bane",
    "recommendedLevel": 200
  },
  {
    "id": 36,
    "monsterId": 272,
    "rarity": 100,
    "bossType": "Bane",
    "recommendedLevel": 200
  },
  {
    "id": 37,
    "monsterId": 273,
    "rarity": 100,
    "bossType": "Bane",
    "recommendedLevel": 200
  },
  {
    "id": 38,
    "monsterId": 274,
    "rarity": 100,
    "bossType": "Bane",
    "recommendedLevel": 200
  },
  {
    "id": 39,
    "monsterId": 275,
    "rarity": 100,
    "bossType": "Bane",
    "recommendedLevel": 200
  },
  {
    "id": 40,
    "monsterId": 276,
    "rarity": 30,
    "bossType": "Archfoe",
    "recommendedLevel": 250
  },
  {
    "id": 41,
    "monsterId": 277,
    "rarity": 30,
    "bossType": "Archfoe",
    "recommendedLevel": 250
  },
  {
    "id": 42,
    "monsterId": 278,
    "rarity": 100,
    "bossType": "Bane",
    "recommendedLevel": 300
  },
  {
    "id": 43,
    "monsterId": 279,
    "rarity": 100,
    "bossType": "Bane",
    "recommendedLevel": 300
  },
  {
    "id": 44,
    "monsterId": 280,
    "rarity": 100,
    "bossType": "Bane",
    "recommendedLevel": 300
  },
  {
    "id": 45,
    "monsterId": 368,
    "rarity": 5,
    "bossType": "Nemesis",
    "recommendedLevel": 300
  },
  {
    "id": 46,
    "monsterId": 369,
    "rarity": 5,
    "bossType": "Nemesis",
    "recommendedLevel": 400
  },
  {
    "id": 47,
    "monsterId": 370,
    "rarity": 5,
    "bossType": "Nemesis",
    "recommendedLevel": 350
  },
  {
    "id": 48,
    "monsterId": 371,
    "rarity": 5,
    "bossType": "Nemesis",
    "recommendedLevel": 350
  }
];
