// Auto-generated by scripts/generate-game-data.mjs
// Do not edit manually. Run: npm run generate:game-data
// Generated at: 2026-07-15T02:47:45.897Z
// Game data version: 79323581daae3bb1
// Static data version: a9a9d3105392ff90
// Source bundle: https://stonegy-online.com/_next/static/chunks/pages/_app-f431d076605ee183.js

export const CRAFT = {
  "types": [
    {
      "craftType": 1,
      "label": "UMBRAL"
    },
    {
      "craftType": 2,
      "label": "CRYSTALLINE TOKEN"
    },
    {
      "craftType": 4,
      "label": "GOLD TOKEN"
    },
    {
      "craftType": 3,
      "label": "SPECIAL"
    }
  ],
  "umbralFamilies": [
    {
      "key": "blade",
      "crudeItemId": 405,
      "umbralItemId": 413,
      "masterItemId": 421
    },
    {
      "key": "slayer",
      "crudeItemId": 406,
      "umbralItemId": 414,
      "masterItemId": 422
    },
    {
      "key": "axe",
      "crudeItemId": 407,
      "umbralItemId": 415,
      "masterItemId": 423
    },
    {
      "key": "chopper",
      "crudeItemId": 408,
      "umbralItemId": 416,
      "masterItemId": 424
    },
    {
      "key": "hammer",
      "crudeItemId": 409,
      "umbralItemId": 417,
      "masterItemId": 425
    },
    {
      "key": "mace",
      "crudeItemId": 410,
      "umbralItemId": 418,
      "masterItemId": 426
    },
    {
      "key": "bow",
      "crudeItemId": 411,
      "umbralItemId": 419,
      "masterItemId": 427
    },
    {
      "key": "spellbook",
      "crudeItemId": 412,
      "umbralItemId": 420,
      "masterItemId": 428
    }
  ],
  "recipes": [
    {
      "id": 1001,
      "craftType": 1,
      "action": "create",
      "label": "Create blade",
      "successChancePercent": 70,
      "costs": [
        {
          "itemId": 404,
          "amount": 1
        },
        {
          "itemId": 389,
          "amount": 20
        }
      ],
      "resultItemId": 405
    },
    {
      "id": 1002,
      "craftType": 1,
      "action": "create",
      "label": "Create slayer",
      "successChancePercent": 70,
      "costs": [
        {
          "itemId": 404,
          "amount": 1
        },
        {
          "itemId": 389,
          "amount": 20
        }
      ],
      "resultItemId": 406
    },
    {
      "id": 1003,
      "craftType": 1,
      "action": "create",
      "label": "Create axe",
      "successChancePercent": 70,
      "costs": [
        {
          "itemId": 404,
          "amount": 1
        },
        {
          "itemId": 389,
          "amount": 20
        }
      ],
      "resultItemId": 407
    },
    {
      "id": 1004,
      "craftType": 1,
      "action": "create",
      "label": "Create chopper",
      "successChancePercent": 70,
      "costs": [
        {
          "itemId": 404,
          "amount": 1
        },
        {
          "itemId": 389,
          "amount": 20
        }
      ],
      "resultItemId": 408
    },
    {
      "id": 1005,
      "craftType": 1,
      "action": "create",
      "label": "Create hammer",
      "successChancePercent": 70,
      "costs": [
        {
          "itemId": 404,
          "amount": 1
        },
        {
          "itemId": 389,
          "amount": 20
        }
      ],
      "resultItemId": 409
    },
    {
      "id": 1006,
      "craftType": 1,
      "action": "create",
      "label": "Create mace",
      "successChancePercent": 70,
      "costs": [
        {
          "itemId": 404,
          "amount": 1
        },
        {
          "itemId": 389,
          "amount": 20
        }
      ],
      "resultItemId": 410
    },
    {
      "id": 1007,
      "craftType": 1,
      "action": "create",
      "label": "Create bow",
      "successChancePercent": 70,
      "costs": [
        {
          "itemId": 404,
          "amount": 1
        },
        {
          "itemId": 389,
          "amount": 20
        }
      ],
      "resultItemId": 411
    },
    {
      "id": 1008,
      "craftType": 1,
      "action": "create",
      "label": "Create spellbook",
      "successChancePercent": 70,
      "costs": [
        {
          "itemId": 404,
          "amount": 1
        },
        {
          "itemId": 389,
          "amount": 20
        }
      ],
      "resultItemId": 412
    },
    {
      "id": 1101,
      "craftType": 1,
      "action": "improve",
      "label": "Improve blade",
      "successChancePercent": 55,
      "costs": [
        {
          "itemId": 405,
          "amount": 1
        },
        {
          "itemId": 389,
          "amount": 75
        }
      ],
      "resultItemId": 413,
      "sourceItemId": 405
    },
    {
      "id": 1102,
      "craftType": 1,
      "action": "improve",
      "label": "Improve slayer",
      "successChancePercent": 55,
      "costs": [
        {
          "itemId": 406,
          "amount": 1
        },
        {
          "itemId": 389,
          "amount": 75
        }
      ],
      "resultItemId": 414,
      "sourceItemId": 406
    },
    {
      "id": 1103,
      "craftType": 1,
      "action": "improve",
      "label": "Improve axe",
      "successChancePercent": 55,
      "costs": [
        {
          "itemId": 407,
          "amount": 1
        },
        {
          "itemId": 389,
          "amount": 75
        }
      ],
      "resultItemId": 415,
      "sourceItemId": 407
    },
    {
      "id": 1104,
      "craftType": 1,
      "action": "improve",
      "label": "Improve chopper",
      "successChancePercent": 55,
      "costs": [
        {
          "itemId": 408,
          "amount": 1
        },
        {
          "itemId": 389,
          "amount": 75
        }
      ],
      "resultItemId": 416,
      "sourceItemId": 408
    },
    {
      "id": 1105,
      "craftType": 1,
      "action": "improve",
      "label": "Improve hammer",
      "successChancePercent": 55,
      "costs": [
        {
          "itemId": 409,
          "amount": 1
        },
        {
          "itemId": 389,
          "amount": 75
        }
      ],
      "resultItemId": 417,
      "sourceItemId": 409
    },
    {
      "id": 1106,
      "craftType": 1,
      "action": "improve",
      "label": "Improve mace",
      "successChancePercent": 55,
      "costs": [
        {
          "itemId": 410,
          "amount": 1
        },
        {
          "itemId": 389,
          "amount": 75
        }
      ],
      "resultItemId": 418,
      "sourceItemId": 410
    },
    {
      "id": 1107,
      "craftType": 1,
      "action": "improve",
      "label": "Improve bow",
      "successChancePercent": 55,
      "costs": [
        {
          "itemId": 411,
          "amount": 1
        },
        {
          "itemId": 389,
          "amount": 75
        }
      ],
      "resultItemId": 419,
      "sourceItemId": 411
    },
    {
      "id": 1108,
      "craftType": 1,
      "action": "improve",
      "label": "Improve spellbook",
      "successChancePercent": 55,
      "costs": [
        {
          "itemId": 412,
          "amount": 1
        },
        {
          "itemId": 389,
          "amount": 75
        }
      ],
      "resultItemId": 420,
      "sourceItemId": 412
    },
    {
      "id": 1201,
      "craftType": 1,
      "action": "transform",
      "label": "Transform blade",
      "successChancePercent": 45,
      "costs": [
        {
          "itemId": 413,
          "amount": 1
        },
        {
          "itemId": 389,
          "amount": 150
        }
      ],
      "resultItemId": 421,
      "sourceItemId": 413,
      "downgradeItemId": 405
    },
    {
      "id": 1202,
      "craftType": 1,
      "action": "transform",
      "label": "Transform slayer",
      "successChancePercent": 45,
      "costs": [
        {
          "itemId": 414,
          "amount": 1
        },
        {
          "itemId": 389,
          "amount": 150
        }
      ],
      "resultItemId": 422,
      "sourceItemId": 414,
      "downgradeItemId": 406
    },
    {
      "id": 1203,
      "craftType": 1,
      "action": "transform",
      "label": "Transform axe",
      "successChancePercent": 45,
      "costs": [
        {
          "itemId": 415,
          "amount": 1
        },
        {
          "itemId": 389,
          "amount": 150
        }
      ],
      "resultItemId": 423,
      "sourceItemId": 415,
      "downgradeItemId": 407
    },
    {
      "id": 1204,
      "craftType": 1,
      "action": "transform",
      "label": "Transform chopper",
      "successChancePercent": 45,
      "costs": [
        {
          "itemId": 416,
          "amount": 1
        },
        {
          "itemId": 389,
          "amount": 150
        }
      ],
      "resultItemId": 424,
      "sourceItemId": 416,
      "downgradeItemId": 408
    },
    {
      "id": 1205,
      "craftType": 1,
      "action": "transform",
      "label": "Transform hammer",
      "successChancePercent": 45,
      "costs": [
        {
          "itemId": 417,
          "amount": 1
        },
        {
          "itemId": 389,
          "amount": 150
        }
      ],
      "resultItemId": 425,
      "sourceItemId": 417,
      "downgradeItemId": 409
    },
    {
      "id": 1206,
      "craftType": 1,
      "action": "transform",
      "label": "Transform mace",
      "successChancePercent": 45,
      "costs": [
        {
          "itemId": 418,
          "amount": 1
        },
        {
          "itemId": 389,
          "amount": 150
        }
      ],
      "resultItemId": 426,
      "sourceItemId": 418,
      "downgradeItemId": 410
    },
    {
      "id": 1207,
      "craftType": 1,
      "action": "transform",
      "label": "Transform bow",
      "successChancePercent": 45,
      "costs": [
        {
          "itemId": 419,
          "amount": 1
        },
        {
          "itemId": 389,
          "amount": 150
        }
      ],
      "resultItemId": 427,
      "sourceItemId": 419,
      "downgradeItemId": 411
    },
    {
      "id": 1208,
      "craftType": 1,
      "action": "transform",
      "label": "Transform spellbook",
      "successChancePercent": 45,
      "costs": [
        {
          "itemId": 420,
          "amount": 1
        },
        {
          "itemId": 389,
          "amount": 150
        }
      ],
      "resultItemId": 428,
      "sourceItemId": 420,
      "downgradeItemId": 412
    },
    {
      "id": 2001,
      "craftType": 2,
      "action": "exchange",
      "label": "Gill Gugel",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 299,
          "amount": 10
        }
      ],
      "resultItemId": 318
    },
    {
      "id": 2002,
      "craftType": 2,
      "action": "exchange",
      "label": "Gill Coat",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 299,
          "amount": 10
        }
      ],
      "resultItemId": 319
    },
    {
      "id": 2003,
      "craftType": 2,
      "action": "exchange",
      "label": "Gill Legs",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 299,
          "amount": 10
        }
      ],
      "resultItemId": 320
    },
    {
      "id": 2004,
      "craftType": 2,
      "action": "exchange",
      "label": "Spellbook of Vigilance",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 299,
          "amount": 10
        }
      ],
      "resultItemId": 321
    },
    {
      "id": 2005,
      "craftType": 2,
      "action": "exchange",
      "label": "Prismatic Helmet",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 299,
          "amount": 10
        }
      ],
      "resultItemId": 322
    },
    {
      "id": 2006,
      "craftType": 2,
      "action": "exchange",
      "label": "Prismatic Armor",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 299,
          "amount": 10
        }
      ],
      "resultItemId": 323
    },
    {
      "id": 2007,
      "craftType": 2,
      "action": "exchange",
      "label": "Prismatic Legs",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 299,
          "amount": 10
        }
      ],
      "resultItemId": 324
    },
    {
      "id": 2008,
      "craftType": 2,
      "action": "exchange",
      "label": "Prismatic Boots",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 299,
          "amount": 10
        }
      ],
      "resultItemId": 325
    },
    {
      "id": 2009,
      "craftType": 2,
      "action": "exchange",
      "label": "Prismatic Shield",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 299,
          "amount": 10
        }
      ],
      "resultItemId": 326
    },
    {
      "id": 2010,
      "craftType": 2,
      "action": "exchange",
      "label": "Iron Loadstone",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 299,
          "amount": 20
        }
      ],
      "resultItemId": 1096
    },
    {
      "id": 2011,
      "craftType": 2,
      "action": "exchange",
      "label": "Glow Wine",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 299,
          "amount": 20
        }
      ],
      "resultItemId": 1097
    },
    {
      "id": 3001,
      "craftType": 3,
      "action": "exchange",
      "label": "Astral Shaper Rune",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 1157,
          "amount": 1
        },
        {
          "itemId": 1158,
          "amount": 1
        },
        {
          "itemId": 1159,
          "amount": 1
        },
        {
          "itemId": 1160,
          "amount": 1
        },
        {
          "itemId": 1161,
          "amount": 1
        },
        {
          "itemId": 1142,
          "amount": 1
        }
      ],
      "resultItemId": 1172
    },
    {
      "id": 3002,
      "craftType": 3,
      "action": "exchange",
      "label": "Falcon Escutcheon",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 606,
          "amount": 1
        },
        {
          "itemId": 600,
          "amount": 1
        },
        {
          "itemId": 601,
          "amount": 1
        }
      ],
      "resultItemId": 1224
    },
    {
      "id": 4001,
      "craftType": 4,
      "action": "exchange",
      "label": "Axe of Destruction",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 578,
          "amount": 50
        }
      ],
      "resultItemId": 1454
    },
    {
      "id": 4002,
      "craftType": 4,
      "action": "exchange",
      "label": "Blade of Destruction",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 578,
          "amount": 50
        }
      ],
      "resultItemId": 1455
    },
    {
      "id": 4003,
      "craftType": 4,
      "action": "exchange",
      "label": "Bow of Destruction",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 578,
          "amount": 50
        }
      ],
      "resultItemId": 1456
    },
    {
      "id": 4004,
      "craftType": 4,
      "action": "exchange",
      "label": "Chopper of Destruction",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 578,
          "amount": 50
        }
      ],
      "resultItemId": 1457
    },
    {
      "id": 4005,
      "craftType": 4,
      "action": "exchange",
      "label": "Crossbow of Destruction",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 578,
          "amount": 50
        }
      ],
      "resultItemId": 1458
    },
    {
      "id": 4006,
      "craftType": 4,
      "action": "exchange",
      "label": "Hammer of Destruction",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 578,
          "amount": 50
        }
      ],
      "resultItemId": 1459
    },
    {
      "id": 4007,
      "craftType": 4,
      "action": "exchange",
      "label": "Mace of Destruction",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 578,
          "amount": 50
        }
      ],
      "resultItemId": 1460
    },
    {
      "id": 4008,
      "craftType": 4,
      "action": "exchange",
      "label": "Nunchaku of Destruction",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 578,
          "amount": 50
        }
      ],
      "resultItemId": 1461
    },
    {
      "id": 4009,
      "craftType": 4,
      "action": "exchange",
      "label": "Rod of Destruction",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 578,
          "amount": 50
        }
      ],
      "resultItemId": 492
    },
    {
      "id": 4010,
      "craftType": 4,
      "action": "exchange",
      "label": "Slayer of Destruction",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 578,
          "amount": 50
        }
      ],
      "resultItemId": 1462
    },
    {
      "id": 4011,
      "craftType": 4,
      "action": "exchange",
      "label": "Wand of Destruction",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 578,
          "amount": 50
        }
      ],
      "resultItemId": 511
    },
    {
      "id": 4012,
      "craftType": 4,
      "action": "exchange",
      "label": "Strike I",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 578,
          "amount": 2
        }
      ],
      "resultItemId": 13,
      "resultAmount": 20,
      "resultItems": [
        {
          "itemId": 13,
          "amount": 20
        }
      ]
    },
    {
      "id": 4013,
      "craftType": 4,
      "action": "exchange",
      "label": "Strike II",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 578,
          "amount": 4
        }
      ],
      "resultItemId": 13,
      "resultAmount": 20,
      "resultItems": [
        {
          "itemId": 13,
          "amount": 20
        },
        {
          "itemId": 258,
          "amount": 25
        }
      ]
    },
    {
      "id": 4014,
      "craftType": 4,
      "action": "exchange",
      "label": "Strike III",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 578,
          "amount": 6
        }
      ],
      "resultItemId": 13,
      "resultAmount": 20,
      "resultItems": [
        {
          "itemId": 13,
          "amount": 20
        },
        {
          "itemId": 258,
          "amount": 25
        },
        {
          "itemId": 899,
          "amount": 5
        }
      ]
    },
    {
      "id": 4015,
      "craftType": 4,
      "action": "exchange",
      "label": "Vampirism I",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 578,
          "amount": 2
        }
      ],
      "resultItemId": 63,
      "resultAmount": 25,
      "resultItems": [
        {
          "itemId": 63,
          "amount": 25
        }
      ]
    },
    {
      "id": 4016,
      "craftType": 4,
      "action": "exchange",
      "label": "Vampirism II",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 578,
          "amount": 4
        }
      ],
      "resultItemId": 63,
      "resultAmount": 25,
      "resultItems": [
        {
          "itemId": 63,
          "amount": 25
        },
        {
          "itemId": 685,
          "amount": 15
        }
      ]
    },
    {
      "id": 4017,
      "craftType": 4,
      "action": "exchange",
      "label": "Vampirism III",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 578,
          "amount": 6
        }
      ],
      "resultItemId": 63,
      "resultAmount": 25,
      "resultItems": [
        {
          "itemId": 63,
          "amount": 25
        },
        {
          "itemId": 685,
          "amount": 15
        },
        {
          "itemId": 724,
          "amount": 5
        }
      ]
    },
    {
      "id": 4018,
      "craftType": 4,
      "action": "exchange",
      "label": "Void I",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 578,
          "amount": 2
        }
      ],
      "resultItemId": 870,
      "resultAmount": 25,
      "resultItems": [
        {
          "itemId": 870,
          "amount": 25
        }
      ]
    },
    {
      "id": 4019,
      "craftType": 4,
      "action": "exchange",
      "label": "Void II",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 578,
          "amount": 4
        }
      ],
      "resultItemId": 870,
      "resultAmount": 25,
      "resultItems": [
        {
          "itemId": 870,
          "amount": 25
        },
        {
          "itemId": 395,
          "amount": 25
        }
      ]
    },
    {
      "id": 4020,
      "craftType": 4,
      "action": "exchange",
      "label": "Void III",
      "successChancePercent": 100,
      "costs": [
        {
          "itemId": 578,
          "amount": 6
        }
      ],
      "resultItemId": 870,
      "resultAmount": 25,
      "resultItems": [
        {
          "itemId": 870,
          "amount": 25
        },
        {
          "itemId": 395,
          "amount": 25
        },
        {
          "itemId": 894,
          "amount": 5
        }
      ]
    }
  ]
};
