// Auto-generated by scripts/generate-game-data.mjs
// Do not edit manually. Run: npm run generate:game-data
// Generated at: 2026-07-07T16:57:54.054Z
// Game data version: 79323581daae3bb1
// Static data version: d73f338ae7b61aa4
// Source bundle: https://stonegy-online.com/_next/static/chunks/pages/_app-e0fdfe126a17b371.js

export const HUNTS = [
  {
    "id": 1,
    "title": "Sewers",
    "monsters": [
      4
    ],
    "mapId": 195,
    "recommendedLevel": 1,
    "maxLure": 2
  },
  {
    "id": 2,
    "title": "Forest",
    "monsters": [
      2,
      5
    ],
    "mapId": 120,
    "recommendedLevel": 2,
    "maxLure": 2,
    "levelMin": 2,
    "monsterWeights": {
      "2": 30
    },
    "blockedTiles": [
      {
        "x": -2,
        "y": 0
      },
      {
        "x": -2,
        "y": -1
      },
      {
        "x": -3,
        "y": 0
      },
      {
        "x": -4,
        "y": 0
      },
      {
        "x": -3,
        "y": 1
      },
      {
        "x": -4,
        "y": 1
      },
      {
        "x": 2,
        "y": 1
      },
      {
        "x": 2,
        "y": 0
      },
      {
        "x": 2,
        "y": -1
      },
      {
        "x": 3,
        "y": -1
      },
      {
        "x": 3,
        "y": 0
      },
      {
        "x": 3,
        "y": 1
      },
      {
        "x": 4,
        "y": 1
      },
      {
        "x": 4,
        "y": 0
      },
      {
        "x": 4,
        "y": -1
      }
    ]
  },
  {
    "id": 5,
    "title": "Darashia Minotaurs Surface",
    "monsters": [
      6
    ],
    "mapId": 8,
    "levelMin": 8,
    "recommendedLevel": 6,
    "maxLure": 3,
    "ambientLight": 1,
    "blockedTiles": [
      {
        "x": 3,
        "y": 0
      },
      {
        "x": 3,
        "y": -1
      },
      {
        "x": 4,
        "y": -1
      },
      {
        "x": 4,
        "y": 0
      },
      {
        "x": 4,
        "y": 1
      },
      {
        "x": -3,
        "y": -1
      },
      {
        "x": -4,
        "y": -1
      }
    ]
  },
  {
    "id": 6,
    "title": "Amazon Camp Venore",
    "monsters": [
      7,
      97
    ],
    "mapId": 112,
    "recommendedLevel": 12,
    "maxLure": 2,
    "levelMin": 8,
    "monsterWeights": {
      "97": 38.76
    },
    "blockedTiles": [
      {
        "x": 4,
        "y": -1
      }
    ]
  },
  {
    "id": 7,
    "title": "Cyclops Mistrock Surface",
    "monsters": [
      8
    ],
    "mapId": 124,
    "recommendedLevel": 35,
    "maxLure": 4,
    "levelMin": 15,
    "blockedTiles": [
      {
        "x": -3,
        "y": -1
      },
      {
        "x": -4,
        "y": -1
      },
      {
        "x": -4,
        "y": 0
      },
      {
        "x": -4,
        "y": 1
      }
    ]
  },
  {
    "id": 8,
    "title": "Daramian Minotaur Pyramid",
    "monsters": [
      11,
      10,
      9
    ],
    "mapId": 103,
    "isPremmium": true,
    "recommendedLevel": 30,
    "levelMin": 12,
    "monsterWeights": {
      "10": 28.44,
      "11": 27.56
    },
    "minLure": 3,
    "maxLure": 5,
    "blockedTiles": [
      {
        "x": 4,
        "y": 1
      },
      {
        "x": -4,
        "y": -1
      },
      {
        "x": -4,
        "y": 0
      },
      {
        "x": -4,
        "y": 1
      }
    ]
  },
  {
    "id": 9,
    "title": "Venore Rotworms",
    "monsters": [
      13,
      14
    ],
    "mapId": 132,
    "levelMin": 8,
    "recommendedLevel": 10,
    "maxLure": 2,
    "monsterWeights": {
      "14": 27.33
    },
    "blockedTiles": [
      {
        "x": -4,
        "y": 1
      },
      {
        "x": -3,
        "y": 1
      }
    ]
  },
  {
    "id": 10,
    "title": "Tiquanda Tarantula Cave",
    "monsters": [
      15
    ],
    "mapId": 114,
    "recommendedLevel": 20,
    "maxLure": 3,
    "levelMin": 14,
    "blockedTiles": [
      {
        "x": 3,
        "y": 1
      },
      {
        "x": 4,
        "y": 1
      },
      {
        "x": -4,
        "y": -1
      },
      {
        "x": -4,
        "y": 0
      },
      {
        "x": -4,
        "y": 1
      }
    ]
  },
  {
    "id": 11,
    "title": "Tomb Floor I",
    "monsters": [
      16,
      17,
      164
    ],
    "mapId": 16,
    "levelMin": 4,
    "recommendedLevel": 5,
    "maxLure": 2,
    "monsterWeights": {
      "17": 30,
      "164": 15
    }
  },
  {
    "id": 12,
    "title": "Tomb Floor II",
    "monsters": [
      16,
      17,
      18,
      20
    ],
    "mapId": 134,
    "recommendedLevel": 19,
    "levelMin": 15,
    "maxLure": 3,
    "monsterWeights": {
      "16": 25,
      "18": 10,
      "20": 20
    },
    "blockedTiles": [
      {
        "x": -3,
        "y": 1
      },
      {
        "x": -4,
        "y": 1
      },
      {
        "x": 4,
        "y": -1
      }
    ]
  },
  {
    "id": 13,
    "title": "Tomb Floor III",
    "monsters": [
      18,
      20,
      22,
      160,
      165
    ],
    "mapId": 135,
    "recommendedLevel": 35,
    "levelMin": 18,
    "minLure": 3,
    "maxLure": 7,
    "monsterWeights": {
      "20": 20,
      "22": 15,
      "160": 5,
      "165": 20
    },
    "isPremmium": true
  },
  {
    "id": 17,
    "title": "Wasp Tower",
    "monsters": [
      27
    ],
    "mapId": 1,
    "recommendedLevel": 7,
    "maxLure": 2,
    "levelMin": 8,
    "blockedTiles": [
      {
        "x": 2,
        "y": -1
      },
      {
        "x": 3,
        "y": -1
      },
      {
        "x": 3,
        "y": 1
      },
      {
        "x": 4,
        "y": 1
      },
      {
        "x": 4,
        "y": 0
      },
      {
        "x": 4,
        "y": -1
      },
      {
        "x": -3,
        "y": -1
      },
      {
        "x": -4,
        "y": -1
      },
      {
        "x": -4,
        "y": 0
      },
      {
        "x": -3,
        "y": 0
      },
      {
        "x": -3,
        "y": 1
      },
      {
        "x": -4,
        "y": 1
      }
    ]
  },
  {
    "id": 18,
    "title": "Dragon Lair",
    "monsters": [
      28
    ],
    "mapId": 22,
    "recommendedLevel": 40,
    "levelMin": 30,
    "maxLure": 2,
    "ambientLight": 0.5
  },
  {
    "id": 19,
    "title": "Elf Quarter",
    "monsters": [
      29,
      30
    ],
    "mapId": 119,
    "ambientLight": 1,
    "recommendedLevel": 17,
    "maxLure": 2,
    "levelMin": 13,
    "monsterWeights": {
      "29": 40.98
    },
    "blockedTiles": [
      {
        "x": -3,
        "y": -1
      },
      {
        "x": -3,
        "y": 1
      },
      {
        "x": 2,
        "y": -1
      },
      {
        "x": 2,
        "y": 1
      }
    ],
    "isPremmium": true
  },
  {
    "id": 20,
    "title": "Shadowthorn",
    "monsters": [
      31,
      29,
      30
    ],
    "mapId": 121,
    "recommendedLevel": 25,
    "minLure": 3,
    "maxLure": 3,
    "levelMin": 12,
    "monsterWeights": {
      "29": 33.33,
      "31": 17.03
    },
    "blockedTiles": [
      {
        "x": -3,
        "y": 1
      },
      {
        "x": -4,
        "y": 1
      },
      {
        "x": 4,
        "y": 1
      }
    ]
  },
  {
    "id": 21,
    "title": "Exotic Cave",
    "monsters": [
      32,
      33
    ],
    "mapId": 113,
    "recommendedLevel": 130,
    "levelMin": 90,
    "maxLure": 6,
    "blockedTiles": [
      {
        "x": 4,
        "y": 1
      },
      {
        "x": -4,
        "y": -1
      },
      {
        "x": -4,
        "y": 0
      },
      {
        "x": -4,
        "y": 1
      }
    ],
    "monsterWeights": {
      "32": 29.63
    },
    "isPremmium": true
  },
  {
    "id": 22,
    "title": "Stonerefiner Cave",
    "monsters": [
      34
    ],
    "mapId": 24,
    "recommendedLevel": 45,
    "levelMin": 20,
    "maxLure": 1,
    "ambientLight": 0.4,
    "isPremmium": true
  },
  {
    "id": 23,
    "title": "Dragon Valley",
    "monsters": [
      35,
      28
    ],
    "mapId": 22,
    "recommendedLevel": 90,
    "levelMin": 40,
    "maxLure": 2,
    "monsterWeights": {
      "28": 40
    },
    "isPremmium": true
  },
  {
    "id": 24,
    "title": "Hydras",
    "monsters": [
      36,
      53
    ],
    "mapId": 141,
    "recommendedLevel": 90,
    "levelMin": 50,
    "maxLure": 5,
    "ambientLight": 0.5,
    "monsterWeights": {
      "36": 49.42
    },
    "isPremmium": true
  },
  {
    "id": 25,
    "title": "Cyclopolis",
    "monsters": [
      37,
      8,
      38
    ],
    "mapId": 123,
    "recommendedLevel": 45,
    "minLure": 3,
    "levelMin": 25,
    "maxLure": 5,
    "blockedTiles": [
      {
        "x": 4,
        "y": 1
      },
      {
        "x": -3,
        "y": 1
      },
      {
        "x": -4,
        "y": 1
      }
    ],
    "monsterWeights": {
      "37": 23.04,
      "38": 30.35
    }
  },
  {
    "id": 26,
    "title": "Warlocks",
    "monsters": [
      39
    ],
    "mapId": 910,
    "recommendedLevel": 70,
    "levelMin": 55,
    "maxLure": 1,
    "blockedTiles": [
      {
        "x": 3,
        "y": 1
      },
      {
        "x": 4,
        "y": 1
      },
      {
        "x": -3,
        "y": 1
      },
      {
        "x": -3,
        "y": 0
      },
      {
        "x": -3,
        "y": -1
      },
      {
        "x": -4,
        "y": -1
      },
      {
        "x": -4,
        "y": 0
      },
      {
        "x": -4,
        "y": 1
      }
    ]
  },
  {
    "id": 27,
    "title": "Giant Spider Cave",
    "monsters": [
      40
    ],
    "mapId": 110,
    "recommendedLevel": 80,
    "maxLure": 3,
    "levelMin": 40
  },
  {
    "id": 28,
    "title": "Demons",
    "monsters": [
      1
    ],
    "mapId": 105,
    "recommendedLevel": 150,
    "levelMin": 90,
    "maxLure": 3,
    "isPremmium": true
  },
  {
    "id": 29,
    "title": "Wyrms",
    "monsters": [
      41
    ],
    "mapId": 129,
    "recommendedLevel": 80,
    "levelMin": 45,
    "maxLure": 5,
    "blockedTiles": [
      {
        "x": -4,
        "y": -1
      },
      {
        "x": 4,
        "y": 0
      },
      {
        "x": 4,
        "y": -1
      },
      {
        "x": 4,
        "y": 1
      },
      {
        "x": -3,
        "y": -1
      }
    ],
    "isPremmium": true
  },
  {
    "id": 30,
    "title": "Elder Wyrms II",
    "monsters": [
      42,
      41
    ],
    "mapId": 128,
    "recommendedLevel": 120,
    "levelMin": 80,
    "maxLure": 7,
    "monsterWeights": {
      "42": 24.33
    }
  },
  {
    "id": 32,
    "title": "Hero Fortress",
    "monsters": [
      44,
      49
    ],
    "mapId": 902,
    "levelMin": 25,
    "recommendedLevel": 35,
    "maxLure": 4,
    "monsterWeights": {
      "49": 39.83
    }
  },
  {
    "id": 33,
    "title": "Hero Fortress II",
    "monsters": [
      45,
      44,
      46,
      47
    ],
    "mapId": 100,
    "recommendedLevel": 55,
    "levelMin": 45,
    "maxLure": 7,
    "monsterWeights": {
      "45": 28.79,
      "46": 21.1,
      "47": 16.74
    },
    "isPremmium": true
  },
  {
    "id": 35,
    "title": "Necromancers",
    "monsters": [
      48
    ],
    "mapId": 116,
    "recommendedLevel": 50,
    "levelMin": 30,
    "maxLure": 2,
    "blockedTiles": [
      {
        "x": 2,
        "y": 1
      },
      {
        "x": 3,
        "y": 1
      },
      {
        "x": 3,
        "y": 0
      },
      {
        "x": 3,
        "y": -1
      },
      {
        "x": 4,
        "y": -1
      },
      {
        "x": 4,
        "y": 0
      },
      {
        "x": 4,
        "y": 1
      },
      {
        "x": -2,
        "y": -1
      },
      {
        "x": -3,
        "y": -1
      },
      {
        "x": -3,
        "y": 0
      },
      {
        "x": -3,
        "y": 1
      },
      {
        "x": -4,
        "y": 1
      },
      {
        "x": -4,
        "y": -1
      },
      {
        "x": -4,
        "y": 0
      }
    ],
    "isPremmium": true
  },
  {
    "id": 36,
    "title": "Bog Raiders",
    "monsters": [
      53,
      167
    ],
    "mapId": 117,
    "recommendedLevel": 45,
    "maxLure": 4,
    "levelMin": 30,
    "isPremmium": true,
    "monsterWeights": {
      "167": 18.98
    }
  },
  {
    "id": 37,
    "title": "Feyrist Surface",
    "monsters": [
      175,
      56,
      55,
      57,
      176
    ],
    "mapId": 909,
    "recommendedLevel": 60,
    "levelMin": 30,
    "minLure": 3,
    "maxLure": 4,
    "monsterWeights": {
      "56": 19.4,
      "57": 24.14,
      "175": 19.83,
      "176": 12.07
    },
    "isPremmium": true
  },
  {
    "id": 38,
    "title": "Mutated Rats",
    "monsters": [
      58
    ],
    "mapId": 118,
    "recommendedLevel": 30,
    "levelMin": 18,
    "maxLure": 3,
    "blockedTiles": [
      {
        "x": 4,
        "y": -1
      },
      {
        "x": 2,
        "y": 0
      },
      {
        "x": -2,
        "y": -1
      },
      {
        "x": -2,
        "y": 0
      },
      {
        "x": -2,
        "y": 1
      },
      {
        "x": -3,
        "y": 1
      },
      {
        "x": -3,
        "y": 0
      },
      {
        "x": -3,
        "y": -1
      },
      {
        "x": -4,
        "y": -1
      },
      {
        "x": -4,
        "y": 0
      },
      {
        "x": -4,
        "y": 1
      }
    ],
    "isPremmium": true
  },
  {
    "id": 39,
    "title": "Mutated II",
    "monsters": [
      58,
      59,
      60
    ],
    "mapId": 133,
    "recommendedLevel": 35,
    "maxLure": 4,
    "levelMin": 20,
    "isPremmium": true
  },
  {
    "id": 41,
    "title": "Oramond Minos",
    "monsters": [
      62,
      63,
      64
    ],
    "mapId": 125,
    "recommendedLevel": 80,
    "levelMin": 50,
    "maxLure": 5,
    "blockedTiles": [
      {
        "x": -4,
        "y": -1
      },
      {
        "x": -4,
        "y": 0
      },
      {
        "x": -4,
        "y": 1
      }
    ]
  },
  {
    "id": 42,
    "title": "Glooth Bandits",
    "monsters": [
      65,
      66
    ],
    "mapId": 127,
    "recommendedLevel": 140,
    "levelMin": 80,
    "maxLure": 5,
    "minLure": 3,
    "monsterWeights": {
      "66": 49.33
    }
  },
  {
    "id": 43,
    "title": "Lava Lurker",
    "monsters": [
      67
    ],
    "mapId": 109,
    "recommendedLevel": 100,
    "levelMin": 100,
    "maxLure": 7,
    "minLure": 4,
    "isPremmium": true
  },
  {
    "id": 44,
    "title": "Gazer Spectre",
    "monsters": [
      68
    ],
    "mapId": 102,
    "recommendedLevel": 300,
    "levelMin": 100,
    "maxLure": 7,
    "minLure": 4,
    "isPremmium": true
  },
  {
    "id": 45,
    "title": "Burster Spectre",
    "monsters": [
      69
    ],
    "mapId": 136,
    "recommendedLevel": 300,
    "levelMin": 100,
    "maxLure": 7,
    "minLure": 4,
    "isPremmium": true
  },
  {
    "id": 46,
    "title": "Ripper Spectre",
    "monsters": [
      70
    ],
    "mapId": 140,
    "recommendedLevel": 300,
    "levelMin": 100,
    "maxLure": 7,
    "minLure": 4
  },
  {
    "id": 48,
    "title": "Gnomegate Magma Dungeon",
    "monsters": [
      74,
      73,
      117
    ],
    "mapId": 142,
    "recommendedLevel": 160,
    "levelMin": 130,
    "maxLure": 1,
    "minLure": 1,
    "isPremmium": true,
    "blockedTiles": [
      {
        "x": -3,
        "y": -1
      },
      {
        "x": -4,
        "y": -1
      },
      {
        "x": -4,
        "y": 0
      },
      {
        "x": -3,
        "y": 0
      },
      {
        "x": -3,
        "y": 1
      },
      {
        "x": -4,
        "y": 1
      }
    ]
  },
  {
    "id": 51,
    "title": "Grimvale",
    "monsters": [
      77,
      78,
      79
    ],
    "mapId": 104,
    "recommendedLevel": 120,
    "levelMin": 75,
    "maxLure": 7,
    "minLure": 4,
    "monsterWeights": {
      "77": 34.31,
      "78": 22.72
    },
    "blockedTiles": [
      {
        "x": 4,
        "y": 1
      },
      {
        "x": 3,
        "y": 1
      },
      {
        "x": -3,
        "y": 1
      },
      {
        "x": -4,
        "y": 1
      }
    ],
    "isPremmium": true
  },
  {
    "id": 53,
    "title": "Lizard Chosens",
    "monsters": [
      81
    ],
    "mapId": 111,
    "recommendedLevel": 100,
    "levelMin": 80,
    "maxLure": 5,
    "minLure": 1,
    "isPremmium": true
  },
  {
    "id": 54,
    "title": "Draken Walls",
    "monsters": [
      82,
      83
    ],
    "mapId": 41,
    "recommendedLevel": 250,
    "levelMin": 150,
    "maxLure": 7,
    "minLure": 5,
    "monsterWeights": {
      "83": 41.65
    }
  },
  {
    "id": 55,
    "title": "Ghastly Dragons",
    "monsters": [
      84
    ],
    "mapId": 138,
    "recommendedLevel": 200,
    "levelMin": 100,
    "maxLure": 1,
    "minLure": 1,
    "blockedTiles": [
      {
        "x": 4,
        "y": 1
      }
    ],
    "isPremmium": true
  },
  {
    "id": 56,
    "title": "Draken Abominations",
    "monsters": [
      82,
      83,
      86,
      87
    ],
    "mapId": 911,
    "recommendedLevel": 200,
    "levelMin": 150,
    "maxLure": 2,
    "minLure": 1,
    "blockedTiles": [
      {
        "x": 4,
        "y": 0
      },
      {
        "x": 4,
        "y": 1
      },
      {
        "x": -4,
        "y": -1
      },
      {
        "x": -4,
        "y": 1
      }
    ],
    "monsterWeights": {
      "82": 21.38,
      "83": 25.85,
      "87": 21.91
    },
    "isPremmium": true
  },
  {
    "id": 57,
    "title": "Asura Palace",
    "monsters": [
      88,
      89
    ],
    "mapId": 101,
    "recommendedLevel": 230,
    "levelMin": 120,
    "maxLure": 7,
    "minLure": 4,
    "isPremmium": true,
    "monsterWeights": {
      "88": 47.98
    }
  },
  {
    "id": 58,
    "title": "Lower Roshamuul",
    "monsters": [
      90,
      91
    ],
    "mapId": 122,
    "recommendedLevel": 150,
    "levelMin": 100,
    "maxLure": 7,
    "minLure": 3,
    "monsterWeights": {
      "91": 36.75
    },
    "isPremmium": true
  },
  {
    "id": 59,
    "title": "Lower Roshamuul Surface",
    "monsters": [
      92
    ],
    "mapId": 126,
    "recommendedLevel": 300,
    "levelMin": 180,
    "maxLure": 7,
    "minLure": 3,
    "blockedTiles": [
      {
        "x": 4,
        "y": -1
      }
    ],
    "isPremmium": true
  },
  {
    "id": 60,
    "title": "Summer Court",
    "monsters": [
      120,
      121,
      119
    ],
    "monsterWeights": {
      "119": 15.5,
      "121": 39.16
    },
    "mapId": 904,
    "recommendedLevel": 300,
    "levelMin": 150,
    "maxLure": 8,
    "minLure": 3
  },
  {
    "id": 61,
    "title": "Winter Court",
    "monsters": [
      123,
      124,
      125
    ],
    "monsterWeights": {
      "125": 22.51
    },
    "mapId": 905,
    "recommendedLevel": 300,
    "levelMin": 150,
    "maxLure": 8,
    "minLure": 3
  },
  {
    "id": 62,
    "title": "Asura Vaults (True Asuras)",
    "monsters": [
      126,
      127,
      128
    ],
    "mapId": 107,
    "recommendedLevel": 350,
    "levelMin": 250,
    "maxLure": 8,
    "minLure": 3,
    "monsterWeights": {
      "126": 39.98,
      "127": 10.74
    }
  },
  {
    "id": 63,
    "title": "Nightmare Isles",
    "monsters": [
      129,
      130
    ],
    "mapId": 901,
    "recommendedLevel": 200,
    "levelMin": 130,
    "maxLure": 8,
    "minLure": 5,
    "ambientLight": 0.5,
    "monsterWeights": {
      "129": 46.08
    },
    "blockedTiles": [
      {
        "x": 4,
        "y": -1
      }
    ]
  },
  {
    "id": 64,
    "title": "Gnomegate Crystal Dungeon",
    "monsters": [
      116,
      115,
      114,
      117
    ],
    "mapId": 108,
    "recommendedLevel": 250,
    "levelMin": 130,
    "maxLure": 8,
    "minLure": 5,
    "monsterWeights": {
      "114": 28.79,
      "116": 17.03,
      "117": 24.31
    },
    "blockedTiles": [
      {
        "x": -3,
        "y": 1
      },
      {
        "x": -4,
        "y": 1
      }
    ],
    "isPremmium": true
  },
  {
    "id": 65,
    "title": "Secret Library (Ice Section)",
    "monsters": [
      131,
      132,
      133
    ],
    "mapId": 903,
    "recommendedLevel": 450,
    "levelMin": 350,
    "maxLure": 8,
    "minLure": 4,
    "monsterWeights": {
      "131": 36.43,
      "133": 24.37
    },
    "blockedTiles": [
      {
        "x": 3,
        "y": 1
      },
      {
        "x": 4,
        "y": 1
      }
    ],
    "isPremmium": true
  },
  {
    "id": 66,
    "title": "Ankrahmun Nomads",
    "monsters": [
      134
    ],
    "mapId": 908,
    "recommendedLevel": 15,
    "levelMin": 8,
    "maxLure": 1,
    "minLure": 1,
    "isPremmium": true
  },
  {
    "id": 67,
    "title": "Hell Hub",
    "monsters": [
      135,
      136,
      151,
      1
    ],
    "mapId": 137,
    "monsterWeights": {
      "135": 27.27,
      "136": 30.92,
      "151": 6.95
    },
    "recommendedLevel": 300,
    "levelMin": 200,
    "maxLure": 8,
    "minLure": 4,
    "blockedTiles": [
      {
        "x": -4,
        "y": 0
      },
      {
        "x": -4,
        "y": -1
      }
    ],
    "isPremmium": true
  },
  {
    "id": 68,
    "title": "Orc Fortress",
    "monsters": [
      137,
      138,
      139
    ],
    "mapId": 115,
    "monsterWeights": {
      "138": 29.53,
      "139": 28.26
    },
    "recommendedLevel": 40,
    "levelMin": 30,
    "maxLure": 6,
    "minLure": 4
  },
  {
    "id": 69,
    "title": "Medusa Tower",
    "monsters": [
      142,
      143
    ],
    "mapId": 139,
    "monsterWeights": {
      "142": 39.66
    },
    "recommendedLevel": 250,
    "levelMin": 150,
    "maxLure": 7,
    "minLure": 3,
    "blockedTiles": [
      {
        "x": -4,
        "y": 0
      }
    ],
    "isPremmium": true
  },
  {
    "id": 70,
    "title": "Larva Cave",
    "monsters": [
      147
    ],
    "mapId": 106,
    "recommendedLevel": 8,
    "levelMin": 8,
    "maxLure": 3,
    "minLure": 2,
    "blockedTiles": [
      {
        "x": 3,
        "y": -1
      },
      {
        "x": 4,
        "y": -1
      },
      {
        "x": 3,
        "y": 0
      },
      {
        "x": 4,
        "y": 0
      },
      {
        "x": 3,
        "y": 1
      },
      {
        "x": 4,
        "y": 1
      },
      {
        "x": -3,
        "y": 1
      },
      {
        "x": -3,
        "y": 0
      },
      {
        "x": -3,
        "y": -1
      },
      {
        "x": -4,
        "y": -1
      },
      {
        "x": -4,
        "y": 0
      },
      {
        "x": -4,
        "y": 1
      }
    ]
  },
  {
    "id": 71,
    "title": "Scarab",
    "monsters": [
      146,
      147
    ],
    "mapId": 131,
    "monsterWeights": {
      "147": 34.95
    },
    "recommendedLevel": 15,
    "levelMin": 8,
    "maxLure": 3,
    "minLure": 2,
    "blockedTiles": [
      {
        "x": 4,
        "y": -1
      },
      {
        "x": -3,
        "y": -1
      },
      {
        "x": -3,
        "y": 0
      },
      {
        "x": -4,
        "y": -1
      },
      {
        "x": -4,
        "y": 0
      },
      {
        "x": -4,
        "y": 1
      }
    ],
    "isPremmium": true
  },
  {
    "id": 72,
    "title": "Secret Library (Fire Section)",
    "monsters": [
      148,
      149,
      150
    ],
    "mapId": 906,
    "recommendedLevel": 450,
    "levelMin": 350,
    "maxLure": 8,
    "minLure": 4,
    "monsterWeights": {
      "148": 43,
      "149": 45
    },
    "isPremmium": true
  },
  {
    "id": 73,
    "title": "The Void",
    "monsters": [
      154,
      153,
      152
    ],
    "mapId": 907,
    "recommendedLevel": 200,
    "levelMin": 120,
    "maxLure": 8,
    "minLure": 5,
    "monsterWeights": {
      "153": 29.57,
      "154": 33.06
    }
  },
  {
    "id": 74,
    "title": "Ingol",
    "monsters": [
      155,
      3,
      156,
      157,
      158,
      159
    ],
    "monsterWeights": {
      "3": 12.66,
      "155": 17.04,
      "156": 17.72,
      "158": 12.64,
      "159": 19.86
    },
    "mapId": 130,
    "recommendedLevel": 350,
    "levelMin": 250,
    "maxLure": 8,
    "minLure": 5,
    "isPremmium": true
  },
  {
    "id": 75,
    "title": "Zombies",
    "monsters": [
      200
    ],
    "mapId": 166,
    "recommendedLevel": 30,
    "levelMin": 15,
    "maxLure": 2,
    "minLure": 1,
    "isPremmium": true
  },
  {
    "id": 76,
    "title": "Roaring Lions",
    "monsters": [
      199
    ],
    "mapId": 165,
    "recommendedLevel": 70,
    "levelMin": 40,
    "maxLure": 3,
    "minLure": 2,
    "isPremmium": true
  },
  {
    "id": 77,
    "title": "Crystal Caves",
    "monsters": [
      196,
      202,
      201
    ],
    "mapId": 167,
    "recommendedLevel": 250,
    "levelMin": 120,
    "maxLure": 6,
    "minLure": 5,
    "isPremmium": true
  },
  {
    "id": 78,
    "title": "Beginner Hunt",
    "monsters": [
      203
    ],
    "mapId": 195,
    "levelMin": 1,
    "levelMax": 1,
    "recommendedLevel": 1,
    "minLure": 1,
    "maxLure": 1,
    "tutorialOnly": true,
    "tutorialId": "beginner_hunt"
  },
  {
    "id": 79,
    "title": "Crocodiles",
    "monsters": [
      208,
      209,
      210
    ],
    "mapId": 177,
    "recommendedLevel": 25,
    "levelMin": 20,
    "maxLure": 2,
    "minLure": 1,
    "monsterWeights": {
      "209": 18.92,
      "210": 13.51
    },
    "blockedTiles": [
      {
        "x": -4,
        "y": -1
      },
      {
        "x": -4,
        "y": 0
      },
      {
        "x": -4,
        "y": 1
      }
    ],
    "isPremmium": false
  },
  {
    "id": 80,
    "title": "Ape City",
    "monsters": [
      211,
      212,
      213
    ],
    "mapId": 179,
    "recommendedLevel": 35,
    "levelMin": 25,
    "maxLure": 6,
    "minLure": 5,
    "monsterWeights": {
      "212": 19.02,
      "213": 39.81
    },
    "isPremmium": true
  },
  {
    "id": 81,
    "title": "Terramites",
    "monsters": [
      214
    ],
    "mapId": 181,
    "recommendedLevel": 25,
    "levelMin": 15,
    "maxLure": 1,
    "minLure": 1,
    "isPremmium": true
  },
  {
    "id": 82,
    "title": "Mother of Scarabs lair",
    "monsters": [
      215,
      146,
      49
    ],
    "mapId": 182,
    "recommendedLevel": 80,
    "levelMin": 55,
    "maxLure": 7,
    "minLure": 5,
    "monsterWeights": {
      "49": 35.05,
      "146": 13.21
    },
    "isPremmium": true
  },
  {
    "id": 83,
    "title": "Killer Caiman",
    "monsters": [
      216
    ],
    "mapId": 184,
    "recommendedLevel": 75,
    "levelMin": 50,
    "maxLure": 2,
    "minLure": 1,
    "blockedTiles": [
      {
        "x": 3,
        "y": -1
      },
      {
        "x": 3,
        "y": 0
      },
      {
        "x": 3,
        "y": 1
      }
    ],
    "isPremmium": true
  },
  {
    "id": 84,
    "title": "Zao Plantations",
    "monsters": [
      217,
      218,
      219,
      220,
      221
    ],
    "mapId": 185,
    "recommendedLevel": 200,
    "levelMin": 130,
    "maxLure": 7,
    "minLure": 4,
    "monsterWeights": {
      "218": 7.51,
      "219": 24.37,
      "220": 11.31,
      "221": 9.06
    },
    "isPremmium": true
  },
  {
    "id": 85,
    "title": "Hellspawns",
    "monsters": [
      222
    ],
    "mapId": 186,
    "recommendedLevel": 120,
    "levelMin": 70,
    "maxLure": 3,
    "minLure": 1,
    "isPremmium": true
  },
  {
    "id": 86,
    "title": "Ruins Of Krailos",
    "monsters": [
      223,
      192,
      61
    ],
    "mapId": 188,
    "recommendedLevel": 110,
    "levelMin": 65,
    "maxLure": 5,
    "minLure": 3,
    "monsterWeights": {
      "61": 42.22,
      "192": 3.27
    },
    "isPremmium": true
  },
  {
    "id": 87,
    "title": "Behemoths",
    "monsters": [
      224
    ],
    "mapId": 189,
    "recommendedLevel": 130,
    "levelMin": 80,
    "maxLure": 3,
    "minLure": 1,
    "isPremmium": true
  },
  {
    "id": 88,
    "title": "Sea Serpents",
    "monsters": [
      225,
      226
    ],
    "mapId": 190,
    "recommendedLevel": 130,
    "levelMin": 90,
    "maxLure": 4,
    "minLure": 2,
    "monsterWeights": {
      "225": 42.76
    },
    "isPremmium": true
  },
  {
    "id": 89,
    "title": "Crystal Spiders",
    "monsters": [
      201,
      202
    ],
    "mapId": 183,
    "recommendedLevel": 55,
    "levelMin": 45,
    "maxLure": 2,
    "minLure": 1,
    "monsterWeights": {
      "202": 48.07
    },
    "blockedTiles": [
      {
        "x": 4,
        "y": -1
      }
    ],
    "isPremmium": false
  },
  {
    "id": 90,
    "title": "Stone Golems",
    "monsters": [
      163,
      227
    ],
    "mapId": 180,
    "recommendedLevel": 35,
    "levelMin": 25,
    "maxLure": 3,
    "minLure": 2,
    "monsterWeights": {
      "163": 47.49
    },
    "isPremmium": false
  },
  {
    "id": 91,
    "title": "Gargoyle Sanctuary",
    "monsters": [
      19,
      15,
      228,
      163
    ],
    "mapId": 178,
    "recommendedLevel": 30,
    "levelMin": 23,
    "maxLure": 4,
    "minLure": 2,
    "monsterWeights": {
      "15": 18.07,
      "163": 19.76,
      "228": 18.4
    },
    "isPremmium": true
  },
  {
    "id": 92,
    "title": "Lizard City",
    "monsters": [
      231,
      221,
      229
    ],
    "mapId": 187,
    "recommendedLevel": 130,
    "levelMin": 90,
    "maxLure": 7,
    "minLure": 5,
    "monsterWeights": {
      "221": 26.7,
      "229": 17.33
    },
    "isPremmium": true
  },
  {
    "id": 93,
    "title": "Nightmares",
    "monsters": [
      192,
      223
    ],
    "mapId": 194,
    "recommendedLevel": 120,
    "levelMin": 70,
    "maxLure": 3,
    "minLure": 2,
    "monsterWeights": {
      "223": 48.22
    },
    "isPremmium": true
  },
  {
    "id": 94,
    "title": "Coryms",
    "monsters": [
      232,
      233,
      234
    ],
    "mapId": 196,
    "recommendedLevel": 30,
    "levelMin": 15,
    "maxLure": 4,
    "minLure": 2,
    "monsterWeights": {
      "232": 27.03,
      "233": 36.04
    },
    "isPremmium": false
  },
  {
    "id": 95,
    "title": "Carniphila",
    "monsters": [
      204,
      205,
      206,
      207
    ],
    "mapId": 176,
    "recommendedLevel": 35,
    "levelMin": 28,
    "maxLure": 3,
    "minLure": 2,
    "monsterWeights": {
      "205": 13.12,
      "206": 18.49,
      "207": 11.13
    },
    "isPremmium": true
  },
  {
    "id": 96,
    "title": "Gnomegate Fungus Dungeon",
    "monsters": [
      235,
      236,
      237,
      238
    ],
    "mapId": 232,
    "recommendedLevel": 200,
    "levelMin": 100,
    "maxLure": 7,
    "minLure": 2,
    "monsterWeights": {
      "236": 14.75,
      "237": 12.77,
      "238": 32.71
    },
    "blockedTiles": [
      {
        "x": 3,
        "y": 0
      },
      {
        "x": 4,
        "y": 0
      },
      {
        "x": 4,
        "y": 1
      },
      {
        "x": 3,
        "y": 1
      }
    ],
    "isPremmium": true
  },
  {
    "id": 97,
    "title": "Yielothax",
    "monsters": [
      240
    ],
    "mapId": 197,
    "recommendedLevel": 90,
    "levelMin": 75,
    "maxLure": 1,
    "minLure": 3,
    "blockedTiles": [
      {
        "x": 4,
        "y": -1
      },
      {
        "x": 4,
        "y": 0
      },
      {
        "x": 4,
        "y": 1
      },
      {
        "x": -4,
        "y": 1
      }
    ],
    "isPremmium": true
  },
  {
    "id": 98,
    "title": "Grim Reapers",
    "monsters": [
      241
    ],
    "mapId": 199,
    "recommendedLevel": 180,
    "levelMin": 130,
    "maxLure": 3,
    "minLure": 1,
    "blockedTiles": [
      {
        "x": 4,
        "y": 1
      }
    ],
    "isPremmium": true
  },
  {
    "id": 99,
    "title": "Werehyaenas",
    "monsters": [
      242,
      243
    ],
    "mapId": 200,
    "recommendedLevel": 200,
    "levelMin": 140,
    "maxLure": 7,
    "minLure": 3,
    "monsterWeights": {
      "243": 37.89
    },
    "blockedTiles": [
      {
        "x": 4,
        "y": 1
      },
      {
        "x": 4,
        "y": 0
      },
      {
        "x": 4,
        "y": -1
      }
    ],
    "isPremmium": true
  },
  {
    "id": 100,
    "title": "Werelions",
    "monsters": [
      244,
      245,
      246
    ],
    "mapId": 201,
    "recommendedLevel": 350,
    "levelMin": 250,
    "maxLure": 4,
    "minLure": 7,
    "monsterWeights": {
      "244": 42.54,
      "246": 12.05
    },
    "isPremmium": true
  },
  {
    "id": 101,
    "title": "Cults",
    "monsters": [
      247,
      248,
      249,
      250
    ],
    "mapId": 202,
    "recommendedLevel": 35,
    "levelMin": 25,
    "maxLure": 2,
    "minLure": 1,
    "monsterWeights": {
      "247": 26.7,
      "249": 21.47,
      "250": 15.18
    },
    "blockedTiles": [
      {
        "x": 3,
        "y": -1
      },
      {
        "x": 3,
        "y": 1
      },
      {
        "x": -2,
        "y": -1
      },
      {
        "x": -2,
        "y": 1
      }
    ],
    "isPremmium": false
  },
  {
    "id": 102,
    "title": "Goanna",
    "monsters": [
      108,
      109,
      111,
      112
    ],
    "mapId": 193,
    "recommendedLevel": 400,
    "levelMin": 300,
    "maxLure": 7,
    "minLure": 6,
    "monsterWeights": {
      "108": 29.56,
      "109": 17.61,
      "112": 23.27
    },
    "isPremmium": true
  },
  {
    "id": 103,
    "title": "Killmaresh Catacombs",
    "monsters": [
      113,
      251
    ],
    "mapId": 204,
    "recommendedLevel": 400,
    "levelMin": 300,
    "maxLure": 7,
    "minLure": 4,
    "monsterWeights": {
      "251": 45.53
    },
    "blockedTiles": [
      {
        "x": 3,
        "y": 1
      },
      {
        "x": -4,
        "y": 1
      }
    ],
    "isPremmium": true
  },
  {
    "id": 104,
    "title": "Pirates",
    "monsters": [
      281,
      282,
      283,
      284
    ],
    "mapId": 245,
    "recommendedLevel": 50,
    "levelMin": 25,
    "maxLure": 7,
    "minLure": 5,
    "monsterWeights": {
      "281": 28.14,
      "283": 22.16,
      "284": 18.32
    },
    "blockedTiles": [
      {
        "x": -4,
        "y": 1
      }
    ],
    "isPremmium": true
  },
  {
    "id": 105,
    "title": "Hive",
    "monsters": [
      285,
      286,
      287,
      288
    ],
    "mapId": 246,
    "recommendedLevel": 130,
    "levelMin": 90,
    "maxLure": 7,
    "minLure": 4,
    "monsterWeights": {
      "286": 29.96,
      "287": 24.39,
      "288": 13.2
    },
    "isPremmium": true
  },
  {
    "id": 106,
    "title": "Gloom Wolfs",
    "monsters": [
      289,
      290
    ],
    "mapId": 247,
    "recommendedLevel": 30,
    "levelMin": 15,
    "maxLure": 3,
    "minLure": 2,
    "monsterWeights": {
      "290": 42.3
    },
    "blockedTiles": [
      {
        "x": 5,
        "y": 0
      },
      {
        "x": 4,
        "y": -1
      }
    ],
    "isPremmium": false
  },
  {
    "id": 107,
    "title": "Swamp Trolls",
    "monsters": [
      291
    ],
    "mapId": 248,
    "recommendedLevel": 8,
    "levelMin": 8,
    "maxLure": 3,
    "minLure": 1,
    "isPremmium": false
  },
  {
    "id": 108,
    "title": "Rorcs",
    "monsters": [
      292
    ],
    "mapId": 249,
    "recommendedLevel": 25,
    "levelMin": 13,
    "maxLure": 2,
    "minLure": 1,
    "isPremmium": false
  },
  {
    "id": 109,
    "title": "Ghostlands",
    "monsters": [
      180,
      165,
      18,
      293
    ],
    "mapId": 250,
    "recommendedLevel": 60,
    "levelMin": 35,
    "maxLure": 4,
    "minLure": 2,
    "monsterWeights": {
      "18": 19.7,
      "165": 12.12,
      "293": 15.91
    },
    "isPremmium": false
  },
  {
    "id": 110,
    "title": "Putrid Mummy",
    "monsters": [
      294,
      49
    ],
    "mapId": 251,
    "recommendedLevel": 90,
    "levelMin": 60,
    "maxLure": 5,
    "minLure": 2,
    "monsterWeights": {
      "49": 21.58
    },
    "isPremmium": true
  },
  {
    "id": 111,
    "title": "Marsh Stalkers",
    "monsters": [
      207,
      295,
      296,
      297
    ],
    "mapId": 252,
    "recommendedLevel": 8,
    "levelMin": 8,
    "maxLure": 4,
    "minLure": 2,
    "monsterWeights": {
      "207": 7.4,
      "295": 7.98,
      "296": 40.35
    },
    "isPremmium": false
  },
  {
    "id": 112,
    "title": "Formorgar Mines",
    "monsters": [
      145,
      191,
      192,
      194
    ],
    "mapId": 262,
    "recommendedLevel": 250,
    "levelMin": 150,
    "maxLure": 3,
    "minLure": 5,
    "monsterWeights": {
      "145": 19.74,
      "191": 13.68,
      "194": 27.63
    },
    "isPremmium": true
  },
  {
    "id": 113,
    "title": "Quaras",
    "monsters": [
      299,
      300,
      301,
      302,
      303
    ],
    "mapId": 261,
    "recommendedLevel": 130,
    "levelMin": 80,
    "maxLure": 7,
    "minLure": 5,
    "monsterWeights": {
      "299": 17.92,
      "300": 8.78,
      "302": 27.33,
      "303": 10.05
    },
    "isPremmium": true
  },
  {
    "id": 114,
    "title": "The Void",
    "monsters": [
      152,
      153,
      304,
      154
    ],
    "mapId": 263,
    "recommendedLevel": 300,
    "levelMin": 180,
    "maxLure": 7,
    "minLure": 5,
    "monsterWeights": {
      "153": 22.09,
      "154": 26.61,
      "304": 23.13
    },
    "isPremmium": true
  },
  {
    "id": 115,
    "title": "Mino Mountain Hideout",
    "monsters": [
      305,
      306,
      62,
      63,
      254,
      64
    ],
    "mapId": 260,
    "recommendedLevel": 200,
    "levelMin": 100,
    "maxLure": 7,
    "minLure": 5,
    "monsterWeights": {
      "62": 20.67,
      "64": 19.24,
      "254": 10.63,
      "305": 9.44,
      "306": 8.96
    },
    "blockedTiles": [
      {
        "x": 3,
        "y": 1
      },
      {
        "x": 3,
        "y": 0
      },
      {
        "x": 3,
        "y": -1
      },
      {
        "x": 4,
        "y": -1
      },
      {
        "x": 4,
        "y": 1
      },
      {
        "x": 4,
        "y": 0
      },
      {
        "x": -3,
        "y": -1
      },
      {
        "x": -4,
        "y": -1
      }
    ],
    "isPremmium": true
  },
  {
    "id": 116,
    "title": "Krailos Steppe",
    "monsters": [
      308,
      307,
      309,
      141,
      140
    ],
    "mapId": 259,
    "recommendedLevel": 80,
    "levelMin": 45,
    "maxLure": 4,
    "minLure": 3,
    "monsterWeights": {
      "140": 15.61,
      "141": 26.83,
      "307": 8.78,
      "309": 19.02
    },
    "blockedTiles": [
      {
        "x": -2,
        "y": 1
      },
      {
        "x": -3,
        "y": 1
      },
      {
        "x": -3,
        "y": -1
      },
      {
        "x": -4,
        "y": -1
      }
    ],
    "isPremmium": true
  },
  {
    "id": 117,
    "title": "Frost Troll",
    "monsters": [
      310,
      311,
      312,
      313
    ],
    "mapId": 206,
    "recommendedLevel": 8,
    "levelMin": 8,
    "maxLure": 3,
    "minLure": 1,
    "monsterWeights": {
      "311": 28.34,
      "312": 16.3,
      "313": 13.2
    },
    "blockedTiles": [
      {
        "x": 4,
        "y": 1
      },
      {
        "x": -4,
        "y": -1
      },
      {
        "x": -4,
        "y": 1
      }
    ],
    "isPremmium": false
  },
  {
    "id": 118,
    "title": "Mammoth",
    "monsters": [
      314,
      311,
      312,
      315
    ],
    "mapId": 205,
    "recommendedLevel": 12,
    "levelMin": 11,
    "maxLure": 3,
    "minLure": 1,
    "monsterWeights": {
      "311": 30.23,
      "312": 16.22,
      "315": 12.5
    },
    "isPremmium": false
  },
  {
    "id": 119,
    "title": "Barbarian Camp",
    "monsters": [
      316,
      317,
      318
    ],
    "mapId": 210,
    "recommendedLevel": 35,
    "levelMin": 18,
    "maxLure": 5,
    "minLure": 3,
    "monsterWeights": {
      "317": 25.32
    },
    "blockedTiles": [
      {
        "x": -3,
        "y": 1
      }
    ],
    "isPremmium": false,
    "unlockedByDefault": false
  },
  {
    "id": 120,
    "title": "Frost Giants",
    "monsters": [
      323,
      324
    ],
    "mapId": 214,
    "recommendedLevel": 40,
    "levelMin": 25,
    "maxLure": 2,
    "minLure": 1,
    "isPremmium": false,
    "unlockedByDefault": false
  },
  {
    "id": 121,
    "title": "Drefia Vampires",
    "monsters": [
      22,
      21,
      325,
      200
    ],
    "mapId": 256,
    "recommendedLevel": 70,
    "levelMin": 35,
    "maxLure": 4,
    "minLure": 2,
    "monsterWeights": {
      "21": 32.91,
      "200": 7.27,
      "325": 8.18
    },
    "blockedTiles": [
      {
        "x": 4,
        "y": -1
      },
      {
        "x": -4,
        "y": 1
      }
    ],
    "isPremmium": true
  },
  {
    "id": 122,
    "title": "Weakened Frazzlemaw",
    "monsters": [
      326,
      327
    ],
    "mapId": 253,
    "recommendedLevel": 130,
    "levelMin": 80,
    "maxLure": 4,
    "minLure": 2,
    "monsterWeights": {
      "326": 46.2
    },
    "blockedTiles": [
      {
        "x": 4,
        "y": 0
      },
      {
        "x": 4,
        "y": -1
      },
      {
        "x": -3,
        "y": -1
      },
      {
        "x": -4,
        "y": 0
      },
      {
        "x": -4,
        "y": -1
      }
    ],
    "isPremmium": true
  },
  {
    "id": 123,
    "title": "Deeplings",
    "monsters": [
      328,
      329,
      330,
      331,
      332,
      333
    ],
    "mapId": 255,
    "recommendedLevel": 220,
    "levelMin": 150,
    "maxLure": 3,
    "minLure": 2,
    "monsterWeights": {
      "328": 27.37,
      "330": 3.96,
      "331": 22.89,
      "332": 8.95,
      "333": 2.43
    },
    "blockedTiles": [
      {
        "x": 4,
        "y": -1
      },
      {
        "x": 4,
        "y": 0
      },
      {
        "x": 4,
        "y": 1
      },
      {
        "x": -4,
        "y": 1
      }
    ],
    "isPremmium": true
  },
  {
    "id": 124,
    "title": "Wyverns",
    "monsters": [
      334
    ],
    "mapId": 254,
    "recommendedLevel": 45,
    "levelMin": 30,
    "maxLure": 1,
    "minLure": 1,
    "blockedTiles": [
      {
        "x": -3,
        "y": -2
      },
      {
        "x": -4,
        "y": -2
      }
    ],
    "isPremmium": false
  },
  {
    "id": 125,
    "title": "Seacrest Serpents",
    "monsters": [
      336,
      335,
      225,
      337
    ],
    "mapId": 258,
    "recommendedLevel": 130,
    "levelMin": 100,
    "maxLure": 3,
    "minLure": 2,
    "monsterWeights": {
      "335": 11.45,
      "336": 33.99,
      "337": 5.27
    },
    "blockedTiles": [
      {
        "x": -4,
        "y": 0
      },
      {
        "x": -4,
        "y": 1
      }
    ],
    "isPremmium": true
  },
  {
    "id": 126,
    "title": "Forest Fury",
    "monsters": [
      144,
      218,
      366,
      367
    ],
    "mapId": 257,
    "recommendedLevel": 50,
    "levelMin": 30,
    "maxLure": 6,
    "minLure": 3,
    "monsterWeights": {
      "144": 36.03,
      "366": 11.03,
      "367": 21.32
    },
    "blockedTiles": [
      {
        "x": -4,
        "y": 1
      },
      {
        "x": -3,
        "y": -1
      }
    ],
    "isPremmium": true
  }
];
