// Auto-generated by scripts/generate-game-data.mjs
// Do not edit manually. Run: npm run generate:game-data
// Generated at: 2026-07-07T16:57:54.054Z
// Game data version: 79323581daae3bb1
// Static data version: d73f338ae7b61aa4
// Source bundle: https://stonegy-online.com/_next/static/chunks/pages/_app-e0fdfe126a17b371.js

export const QUESTS = [
  {
    "id": 1,
    "title": "Esconderijo dos Ladrões Nômades",
    "description": "Recentemente, um bando de ladrões nômades roubou algo muito valioso de nós. Encontre o esconderijo deles, elimine a ameaça e você será recompensado por sua coragem.",
    "levelMin": 15,
    "premium": true,
    "repeatPolicy": {
      "type": "never"
    },
    "missions": [
      {
        "id": 1,
        "title": "Abrindo o Caminho",
        "description": "A entrada do esconderijo está protegida por um antigo mecanismo. Reúna os itens necessários para destravar a passagem e permitir o acesso ao covil dos ladrões.",
        "type": "deliver_items",
        "deliveryItems": [
          {
            "itemId": 261,
            "amount": 1
          },
          {
            "itemId": 868,
            "amount": 1
          }
        ]
      },
      {
        "id": 2,
        "title": "Invasão ao Esconderijo",
        "description": "Com a passagem liberada, entre no esconderijo dos ladrões nômades e derrote todos que estiverem protegendo o local.",
        "type": "current_hunt",
        "rewards": [
          {
            "id": "1",
            "type": "gold",
            "amount": 10000
          },
          {
            "id": "2",
            "type": "item",
            "amount": 2,
            "itemId": 104
          }
        ],
        "rooms": [
          {
            "id": 1,
            "title": "Hideout Entrance",
            "ambientLight": 0.3,
            "mapId": 912,
            "waves": [
              {
                "minMonsters": 2,
                "maxMonsters": 2,
                "monsterIds": [
                  134
                ]
              }
            ]
          },
          {
            "id": 2,
            "title": "Hideout Dining Hall",
            "ambientLight": 0.3,
            "mapId": 914,
            "waves": [
              {
                "minMonsters": 4,
                "maxMonsters": 4,
                "monsterIds": [
                  134
                ]
              }
            ]
          },
          {
            "id": 3,
            "title": "Hideout Main Room",
            "ambientLight": 0.3,
            "mapId": 913,
            "waves": [
              {
                "minMonsters": 6,
                "maxMonsters": 6,
                "monsterIds": [
                  134
                ]
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "id": 2,
    "title": "Pirâmide dos Minotauros",
    "description": "A antiga pirâmide ao nordeste de Darashia está infestada por minotauros cada vez mais perigosos. Desça até os níveis mais profundos, enfrente os guardiões da pirâmide e recupere os antigos tesouros protegidos pela múmia dos sarcófagos.",
    "levelMin": 30,
    "premium": true,
    "repeatPolicy": {
      "type": "never"
    },
    "missions": [
      {
        "id": 1,
        "title": "Descida à Pirâmide",
        "description": "Entre na pirâmide dos minotauros e avance pelos andares subterrâneos enfrentando criaturas cada vez mais fortes até encontrar a múmia guardiã dos sarcófagos antigos.",
        "type": "current_hunt",
        "rewards": [
          {
            "id": "1",
            "type": "item",
            "amount": 1,
            "itemId": 250
          },
          {
            "id": "2",
            "type": "item",
            "amount": 1,
            "itemId": 820
          }
        ],
        "rooms": [
          {
            "id": 1,
            "title": "Entrada Subterrânea",
            "ambientLight": 0.35,
            "mapId": 8,
            "waves": [
              {
                "minMonsters": 3,
                "maxMonsters": 5,
                "monsterIds": [
                  6,
                  9
                ]
              }
            ]
          },
          {
            "id": 2,
            "title": "Corredores dos Guardas",
            "ambientLight": 0.6,
            "mapId": 143,
            "waves": [
              {
                "minMonsters": 4,
                "maxMonsters": 6,
                "monsterIds": [
                  9,
                  10
                ]
              }
            ]
          },
          {
            "id": 3,
            "title": "Câmara dos Magos",
            "ambientLight": 0.7,
            "mapId": 144,
            "waves": [
              {
                "minMonsters": 6,
                "maxMonsters": 8,
                "monsterIds": [
                  9,
                  10,
                  11
                ]
              }
            ]
          },
          {
            "id": 4,
            "title": "Sala dos Sarcófagos",
            "ambientLight": 0.7,
            "mapId": 145,
            "waves": [
              {
                "minMonsters": 1,
                "maxMonsters": 1,
                "monsterIds": [
                  18
                ]
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "id": 3,
    "title": "Koshei, o Imortal",
    "description": "Um antigo amuleto foi quebrado e espalhado pelas terras de Darama. Desça às profundezas das catacumbas esquecidas, enfrente criaturas amaldiçoadas e derrote o poderoso Koshei the Deathless antes que sua maldição continue se espalhando.",
    "levelMin": 40,
    "premium": true,
    "repeatPolicy": {
      "type": "never"
    },
    "missions": [
      {
        "id": 1,
        "title": "Preparando a Jornada",
        "description": "Para explorar as catacumbas de Koshei, você precisará reunir os equipamentos necessários para sobreviver aos perigos das profundezas.",
        "type": "deliver_items",
        "deliveryItems": [
          {
            "itemId": 23,
            "amount": 25
          }
        ],
        "deliveryGold": 5000
      },
      {
        "id": 2,
        "title": "Catacumbas de Koshei",
        "description": "Explore as catacumbas ao leste de Darashia, atravesse os caminhos ocultos e enfrente Koshei the Deathless em sua tumba amaldiçoada.",
        "type": "current_hunt",
        "rewards": [
          {
            "id": "1",
            "type": "item",
            "amount": 1,
            "itemId": 970
          },
          {
            "id": "2",
            "type": "item",
            "amount": 1,
            "itemId": 971
          }
        ],
        "rooms": [
          {
            "id": 1,
            "title": "Entrada das Catacumbas",
            "ambientLight": 0.8,
            "mapId": 149,
            "waves": [
              {
                "minMonsters": 5,
                "maxMonsters": 7,
                "waveAmount": 3,
                "monsterIds": [
                  17,
                  16,
                  20
                ]
              }
            ]
          },
          {
            "id": 2,
            "title": "Túneis Profanos",
            "ambientLight": 0.8,
            "mapId": 148,
            "waves": [
              {
                "minMonsters": 6,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  177,
                  147,
                  146,
                  18
                ]
              }
            ]
          },
          {
            "id": 3,
            "title": "Corredor dos Mortos",
            "ambientLight": 0.7,
            "mapId": 147,
            "waves": [
              {
                "minMonsters": 7,
                "maxMonsters": 8,
                "waveAmount": 4,
                "monsterIds": [
                  48,
                  49,
                  178,
                  22,
                  19
                ]
              }
            ]
          },
          {
            "id": 4,
            "title": "Tumba de Koshei",
            "ambientLight": 0.7,
            "mapId": 146,
            "waves": [
              {
                "minMonsters": 1,
                "maxMonsters": 1,
                "monsterIds": [
                  179
                ]
              },
              {
                "minMonsters": 1,
                "maxMonsters": 2,
                "monsterIds": [
                  49
                ]
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "id": 4,
    "title": "The Pits of Inferno",
    "description": "Desbrave as profundezas infernais da Pits of Inferno, atravesse corredores dominados por criaturas demoníacas, sobreviva aos tronos dos Ruthless Seven e conquiste uma das recompensas lendárias escondidas no coração do inferno.",
    "levelMin": 80,
    "premium": true,
    "repeatPolicy": {
      "type": "never"
    },
    "missions": [
      {
        "id": 1,
        "title": "Preparação Infernal",
        "description": "Para sobreviver às profundezas infernais, reúna os equipamentos necessários antes de iniciar a jornada.",
        "type": "deliver_items",
        "deliveryItems": [
          {
            "itemId": 56,
            "amount": 50
          }
        ],
        "deliveryGold": 10000
      },
      {
        "id": 2,
        "title": "Pits Of Inferno",
        "description": "Encontre o acesso para as profundezas da Pits of Inferno.",
        "type": "current_hunt",
        "minPlayers": 1,
        "maxPlayers": 4,
        "rewards": [
          {
            "id": "1",
            "type": "item",
            "amount": 1,
            "itemId": 972
          },
          {
            "id": "2",
            "type": "item",
            "amount": 1,
            "itemId": 973
          },
          {
            "id": "3",
            "type": "item",
            "amount": 1,
            "itemId": 974
          },
          {
            "id": "4",
            "type": "item",
            "amount": 1,
            "itemId": 975
          },
          {
            "id": "5",
            "type": "item",
            "amount": 1,
            "itemId": 38
          },
          {
            "id": "6",
            "type": "item",
            "amount": 1,
            "itemId": 979
          },
          {
            "id": "7",
            "type": "item",
            "amount": 1,
            "itemId": 980
          },
          {
            "id": "8",
            "type": "item",
            "amount": 1,
            "itemId": 981
          },
          {
            "id": "9",
            "type": "item",
            "amount": 1,
            "itemId": 982
          }
        ],
        "rewardChoices": [
          {
            "id": "arbalest",
            "label": "Arbalest",
            "rewards": [
              {
                "id": "choice-arbalest",
                "type": "item",
                "amount": 1,
                "itemId": 976
              }
            ]
          },
          {
            "id": "arcane-staff",
            "label": "Arcane Staff",
            "rewards": [
              {
                "id": "choice-arcane-staff",
                "type": "item",
                "amount": 1,
                "itemId": 977
              }
            ]
          },
          {
            "id": "the-avenger",
            "label": "The Avenger",
            "rewards": [
              {
                "id": "choice-the-avenger",
                "type": "item",
                "amount": 1,
                "itemId": 978
              }
            ]
          }
        ],
        "rooms": [
          {
            "id": 1,
            "title": "Entrada Infernal",
            "ambientLight": 0.8,
            "mapId": 150,
            "waves": [
              {
                "minMonsters": 4,
                "maxMonsters": 5,
                "waveAmount": 6,
                "monsterIds": [
                  35
                ]
              }
            ]
          },
          {
            "id": 2,
            "title": "Alavanca 1",
            "ambientLight": 0.7,
            "mapId": 151,
            "waves": [
              {
                "minMonsters": 4,
                "maxMonsters": 6,
                "waveAmount": 2,
                "monsterIds": [
                  188,
                  145
                ]
              },
              {
                "minMonsters": 5,
                "maxMonsters": 7,
                "waveAmount": 2,
                "monsterIds": [
                  188,
                  194
                ]
              }
            ]
          },
          {
            "id": 3,
            "title": "Alavanca 2",
            "ambientLight": 0.8,
            "mapId": 152,
            "waves": [
              {
                "minMonsters": 4,
                "maxMonsters": 6,
                "waveAmount": 2,
                "monsterIds": [
                  184,
                  145
                ]
              },
              {
                "minMonsters": 5,
                "maxMonsters": 7,
                "waveAmount": 2,
                "monsterIds": [
                  184,
                  194
                ]
              }
            ]
          },
          {
            "id": 4,
            "title": "Alavanca 3",
            "ambientLight": 0.8,
            "mapId": 153,
            "waves": [
              {
                "minMonsters": 5,
                "maxMonsters": 7,
                "waveAmount": 2,
                "monsterIds": [
                  185,
                  191
                ]
              },
              {
                "minMonsters": 6,
                "maxMonsters": 8,
                "waveAmount": 2,
                "monsterIds": [
                  185,
                  188
                ]
              }
            ]
          },
          {
            "id": 5,
            "title": "Alavanca 4",
            "ambientLight": 0.8,
            "mapId": 151,
            "waves": [
              {
                "minMonsters": 5,
                "maxMonsters": 7,
                "waveAmount": 2,
                "monsterIds": [
                  183,
                  191
                ]
              },
              {
                "minMonsters": 6,
                "maxMonsters": 8,
                "waveAmount": 2,
                "monsterIds": [
                  183,
                  145
                ]
              }
            ]
          },
          {
            "id": 6,
            "title": "Alavanca 5",
            "ambientLight": 0.8,
            "mapId": 152,
            "waves": [
              {
                "minMonsters": 5,
                "maxMonsters": 7,
                "waveAmount": 2,
                "monsterIds": [
                  192,
                  196
                ]
              },
              {
                "minMonsters": 6,
                "maxMonsters": 8,
                "waveAmount": 2,
                "monsterIds": [
                  192,
                  185
                ]
              }
            ]
          },
          {
            "id": 7,
            "title": "Alavanca 6",
            "ambientLight": 0.8,
            "mapId": 153,
            "waves": [
              {
                "minMonsters": 5,
                "maxMonsters": 7,
                "waveAmount": 2,
                "monsterIds": [
                  193,
                  181
                ]
              },
              {
                "minMonsters": 6,
                "maxMonsters": 8,
                "waveAmount": 2,
                "monsterIds": [
                  193,
                  191
                ]
              }
            ]
          },
          {
            "id": 8,
            "title": "Alavanca 7",
            "ambientLight": 0.75,
            "mapId": 151,
            "waves": [
              {
                "minMonsters": 6,
                "maxMonsters": 8,
                "waveAmount": 2,
                "monsterIds": [
                  194,
                  184
                ]
              },
              {
                "minMonsters": 7,
                "maxMonsters": 8,
                "waveAmount": 2,
                "monsterIds": [
                  194,
                  182
                ]
              }
            ]
          },
          {
            "id": 9,
            "title": "Alavanca 8",
            "ambientLight": 0.75,
            "mapId": 152,
            "waves": [
              {
                "minMonsters": 6,
                "maxMonsters": 8,
                "waveAmount": 2,
                "monsterIds": [
                  188,
                  183
                ]
              },
              {
                "minMonsters": 7,
                "maxMonsters": 8,
                "waveAmount": 2,
                "monsterIds": [
                  188,
                  186
                ]
              }
            ]
          },
          {
            "id": 10,
            "title": "Alavanca 9",
            "ambientLight": 0.75,
            "mapId": 153,
            "waves": [
              {
                "minMonsters": 6,
                "maxMonsters": 8,
                "waveAmount": 2,
                "monsterIds": [
                  145,
                  191
                ]
              },
              {
                "minMonsters": 7,
                "maxMonsters": 8,
                "waveAmount": 2,
                "monsterIds": [
                  145,
                  189
                ]
              }
            ]
          },
          {
            "id": 11,
            "title": "Alavanca 10",
            "ambientLight": 0.75,
            "mapId": 151,
            "waves": [
              {
                "minMonsters": 6,
                "maxMonsters": 8,
                "waveAmount": 2,
                "monsterIds": [
                  181,
                  196
                ]
              },
              {
                "minMonsters": 7,
                "maxMonsters": 8,
                "waveAmount": 2,
                "monsterIds": [
                  181,
                  187
                ]
              }
            ]
          },
          {
            "id": 12,
            "title": "Alavanca 11",
            "ambientLight": 0.7,
            "mapId": 152,
            "waves": [
              {
                "minMonsters": 7,
                "maxMonsters": 8,
                "waveAmount": 2,
                "monsterIds": [
                  182,
                  194
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 2,
                "monsterIds": [
                  182,
                  184
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "monsterIds": [
                  182,
                  186
                ]
              }
            ]
          },
          {
            "id": 13,
            "title": "Alavanca 12",
            "ambientLight": 0.7,
            "mapId": 153,
            "waves": [
              {
                "minMonsters": 7,
                "maxMonsters": 8,
                "waveAmount": 2,
                "monsterIds": [
                  1,
                  188
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 2,
                "monsterIds": [
                  1,
                  145
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "monsterIds": [
                  1,
                  183
                ]
              }
            ]
          },
          {
            "id": 14,
            "title": "Alavanca 13",
            "ambientLight": 0.7,
            "mapId": 151,
            "waves": [
              {
                "minMonsters": 7,
                "maxMonsters": 8,
                "waveAmount": 2,
                "monsterIds": [
                  189,
                  186
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 2,
                "monsterIds": [
                  189,
                  182
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 2,
                "monsterIds": [
                  189,
                  1
                ]
              }
            ]
          },
          {
            "id": 15,
            "title": "Alavanca 14",
            "ambientLight": 0.7,
            "mapId": 152,
            "waves": [
              {
                "minMonsters": 7,
                "maxMonsters": 8,
                "waveAmount": 2,
                "monsterIds": [
                  187,
                  181
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 2,
                "monsterIds": [
                  187,
                  183
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "monsterIds": [
                  187,
                  1
                ]
              }
            ]
          },
          {
            "id": 16,
            "title": "Alavanca 15",
            "ambientLight": 0.65,
            "mapId": 153,
            "waves": [
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 2,
                "monsterIds": [
                  190,
                  188
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 2,
                "monsterIds": [
                  190,
                  145
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "monsterIds": [
                  190,
                  1
                ]
              }
            ]
          },
          {
            "id": 17,
            "title": "Labirinto Infernal",
            "ambientLight": 0.65,
            "mapId": 155,
            "waves": [
              {
                "minMonsters": 5,
                "maxMonsters": 7,
                "waveAmount": 2,
                "monsterIds": [
                  185,
                  192,
                  196
                ]
              },
              {
                "minMonsters": 6,
                "maxMonsters": 8,
                "waveAmount": 2,
                "monsterIds": [
                  192,
                  196,
                  188
                ]
              },
              {
                "minMonsters": 7,
                "maxMonsters": 8,
                "monsterIds": [
                  185,
                  192,
                  196
                ]
              }
            ]
          },
          {
            "id": 18,
            "title": "Câmara das Alavancas",
            "ambientLight": 0.6,
            "mapId": 154,
            "waves": [
              {
                "minMonsters": 3,
                "maxMonsters": 3,
                "waveAmount": 2,
                "monsterIds": [
                  188
                ]
              },
              {
                "minMonsters": 5,
                "maxMonsters": 7,
                "waveAmount": 3,
                "monsterIds": [
                  188,
                  145,
                  191
                ]
              }
            ]
          },
          {
            "id": 19,
            "title": "Entrada dos Ruthless Seven",
            "ambientLight": 0.6,
            "mapId": 156,
            "waves": [
              {
                "minMonsters": 6,
                "maxMonsters": 8,
                "waveAmount": 2,
                "monsterIds": [
                  193,
                  181,
                  194
                ]
              },
              {
                "minMonsters": 7,
                "maxMonsters": 8,
                "waveAmount": 2,
                "monsterIds": [
                  182,
                  187,
                  193
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 2,
                "monsterIds": [
                  181,
                  194,
                  187
                ]
              }
            ]
          },
          {
            "id": 20,
            "title": "Portais dos Tronos",
            "ambientLight": 0.9,
            "mapId": 157,
            "waves": [
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  193,
                  181,
                  194
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  182,
                  187,
                  193
                ]
              }
            ]
          },
          {
            "id": 21,
            "title": "Trono de Ashfalor",
            "ambientLight": 0.75,
            "mapId": 158,
            "waves": [
              {
                "minMonsters": 6,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  178,
                  1
                ]
              },
              {
                "minMonsters": 7,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  197,
                  1
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  197,
                  178,
                  1
                ]
              }
            ]
          },
          {
            "id": 22,
            "title": "Sala dos Tronos II",
            "ambientLight": 0.9,
            "mapId": 157,
            "waves": [
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  187,
                  182,
                  193
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  181,
                  194,
                  182
                ]
              }
            ]
          },
          {
            "id": 23,
            "title": "Trono de Bazir",
            "ambientLight": 0.75,
            "mapId": 162,
            "waves": [
              {
                "minMonsters": 7,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  192,
                  193
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  1,
                  193
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  192,
                  193,
                  1
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  193,
                  1
                ]
              }
            ]
          },
          {
            "id": 24,
            "title": "Sala dos Tronos III",
            "ambientLight": 0.9,
            "mapId": 157,
            "waves": [
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  187,
                  181,
                  194
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  187,
                  182,
                  193
                ]
              }
            ]
          },
          {
            "id": 25,
            "title": "Trono de Infernatil",
            "ambientLight": 0.85,
            "mapId": 160,
            "waves": [
              {
                "minMonsters": 7,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  188,
                  1
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  188,
                  189
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  188,
                  189,
                  1
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  188,
                  1
                ]
              }
            ]
          },
          {
            "id": 26,
            "title": "Sala dos Tronos IV",
            "ambientLight": 0.9,
            "mapId": 157,
            "waves": [
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  187,
                  182,
                  193
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  187,
                  181,
                  194,
                  182
                ]
              }
            ]
          },
          {
            "id": 27,
            "title": "Trono de Tafariel",
            "ambientLight": 0.75,
            "mapId": 161,
            "waves": [
              {
                "minMonsters": 7,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  180,
                  191
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  183,
                  191
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  183,
                  1,
                  180
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  183,
                  191,
                  1
                ]
              }
            ]
          },
          {
            "id": 28,
            "title": "Sala dos Tronos V",
            "ambientLight": 0.9,
            "mapId": 157,
            "waves": [
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  187,
                  181,
                  194,
                  182
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  187,
                  193,
                  181,
                  182
                ]
              }
            ]
          },
          {
            "id": 29,
            "title": "Trono de Verminor",
            "ambientLight": 0.7,
            "mapId": 163,
            "waves": [
              {
                "minMonsters": 7,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  184,
                  194
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  184,
                  195
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  182,
                  194,
                  184
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  182,
                  195,
                  194
                ]
              }
            ]
          },
          {
            "id": 30,
            "title": "Sala dos Tronos VI",
            "ambientLight": 0.9,
            "mapId": 157,
            "waves": [
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  187,
                  193,
                  181,
                  182
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  187,
                  194,
                  182,
                  193
                ]
              }
            ]
          },
          {
            "id": 31,
            "title": "Trono de Apocalypse",
            "ambientLight": 0.75,
            "mapId": 164,
            "waves": [
              {
                "minMonsters": 7,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  145,
                  186
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  1,
                  145
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  190,
                  186,
                  1
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  190,
                  145,
                  1
                ]
              }
            ]
          },
          {
            "id": 32,
            "title": "Sala dos Tronos VII",
            "ambientLight": 0.9,
            "mapId": 157,
            "waves": [
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  187,
                  194,
                  182,
                  193
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  187,
                  181,
                  194,
                  182
                ]
              }
            ]
          },
          {
            "id": 33,
            "title": "Trono de Pumin",
            "ambientLight": 0.7,
            "mapId": 159,
            "waves": [
              {
                "minMonsters": 7,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  196,
                  181
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  187,
                  1
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  196,
                  181,
                  187
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  1,
                  187,
                  181
                ]
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "id": 5,
    "title": "Bigfoot's Burden (Warzone)",
    "description": "Os gnomos precisam de ajuda para conter ameaças antigas que despertaram nas profundezas. Prove seu valor nas zonas de guerra, enfrente criaturas perigosas e conquiste o respeito daqueles que guardam os segredos da Gnomebase.",
    "levelMin": 80,
    "premium": true,
    "repeatPolicy": {
      "type": "cooldown",
      "cooldownMs": 72000000
    },
    "rewardHighlight": {
      "itemId": 299
    },
    "missions": [
      {
        "id": 1,
        "title": "Warzone I",
        "description": "Derrote as criaturas em Gnomegate Fungus Dungeon",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 235,
            "amount": 200
          },
          {
            "monsterId": 238,
            "amount": 200
          }
        ],
        "rewards": [
          {
            "type": "item",
            "itemId": 1125,
            "amount": 1,
            "id": "gill-necklace"
          },
          {
            "type": "item",
            "itemId": 1126,
            "amount": 1,
            "id": "mucus-plug"
          },
          {
            "type": "item",
            "itemId": 299,
            "amount": 2,
            "id": "major-token"
          },
          {
            "type": "item",
            "itemId": 644,
            "amount": 7,
            "id": "shards"
          },
          {
            "type": "gold",
            "id": "gold",
            "amount": 30000
          }
        ]
      },
      {
        "id": 2,
        "title": "Warzone II",
        "description": "Derrote as criaturas em Gnomegate Magma Dungeon",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 117,
            "amount": 200
          },
          {
            "monsterId": 74,
            "amount": 200
          }
        ],
        "rewards": [
          {
            "type": "item",
            "itemId": 347,
            "amount": 1,
            "id": "prismatic-necklace"
          },
          {
            "type": "item",
            "itemId": 1126,
            "amount": 1,
            "id": "mucus-plug"
          },
          {
            "type": "item",
            "itemId": 299,
            "amount": 2,
            "id": "major-token"
          },
          {
            "type": "item",
            "itemId": 537,
            "amount": 10,
            "id": "shards"
          },
          {
            "type": "gold",
            "id": "gold",
            "amount": 40000
          }
        ]
      },
      {
        "id": 3,
        "title": "Warzone III",
        "description": "Derrote as criaturas em Gnomegate Crystal Dungeon",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 115,
            "amount": 200
          },
          {
            "monsterId": 116,
            "amount": 200
          }
        ],
        "rewards": [
          {
            "type": "item",
            "itemId": 346,
            "amount": 1,
            "id": "prismatic-ring"
          },
          {
            "type": "item",
            "itemId": 1126,
            "amount": 1,
            "id": "mucus-plug"
          },
          {
            "type": "item",
            "itemId": 299,
            "amount": 2,
            "id": "major-token"
          },
          {
            "type": "item",
            "itemId": 310,
            "amount": 12,
            "id": "shards"
          },
          {
            "type": "gold",
            "id": "gold",
            "amount": 50000
          }
        ]
      }
    ]
  },
  {
    "id": 6,
    "title": "Hunting Elite",
    "description": "A Paw and Fur Society procura caçadores capazes de controlar criaturas perigosas que ameaçam o equilíbrio das regiões selvagens. Complete tarefas de caça em sequência, avance nas categorias da sociedade e desbloqueie desafios especiais.",
    "levelMin": 15,
    "premium": true,
    "repeatPolicy": {
      "type": "never"
    },
    "missions": [
      {
        "id": 1,
        "title": "Paw and Fur I - Carniphila",
        "description": "Derrote 450 Carniphilas para iniciar sua jornada na Paw and Fur Society.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 204,
            "amount": 450
          }
        ],
        "rewards": [
          {
            "amount": 5000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 2,
        "title": "Paw and Fur I - Crocodile",
        "description": "Derrote 600 Crocodiles.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 208,
            "amount": 600
          }
        ],
        "rewards": [
          {
            "amount": 5000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 3,
        "title": "Paw and Fur I - Gargoyle",
        "description": "Derrote 400 Gargoyles.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 19,
            "amount": 400
          }
        ],
        "rewards": [
          {
            "amount": 5000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 4,
        "title": "Paw and Fur I - Primatas",
        "description": "Derrote 900 primatas selvagens para continuar sua primeira etapa de caça.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 211,
            "amount": 300
          },
          {
            "monsterId": 213,
            "amount": 300
          },
          {
            "monsterId": 212,
            "amount": 300
          }
        ],
        "rewards": [
          {
            "amount": 5000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 5,
        "title": "Paw and Fur I - Stone Golem",
        "description": "Derrote 400 Stone Golems.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 163,
            "amount": 400
          }
        ],
        "rewards": [
          {
            "amount": 5000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 6,
        "title": "Paw and Fur I - Tarantula",
        "description": "Derrote 600 Tarantulas.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 15,
            "amount": 600
          }
        ],
        "rewards": [
          {
            "amount": 5000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 7,
        "title": "Paw and Fur I - Terramite",
        "description": "Derrote 600 Terramites.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 214,
            "amount": 600
          }
        ],
        "rewards": [
          {
            "amount": 5000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 8,
        "title": "Paw and Fur I - Thornback Tortoise",
        "description": "Derrote 600 Thornback Tortoises.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 228,
            "amount": 600
          }
        ],
        "rewards": [
          {
            "amount": 5000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 9,
        "title": "Paw and Fur I - Carniphila II",
        "description": "Derrote mais 700 Carniphilas para alcançar 20 Hunting Points e liberar a Paw and Fur II.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 204,
            "amount": 700
          }
        ],
        "rewards": [
          {
            "amount": 5000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 10,
        "title": "Paw and Fur II - Ancient Scarab",
        "description": "A Paw and Fur II foi liberada. Derrote 600 Ancient Scarabs para iniciar a segunda categoria.",
        "type": "monster_task",
        "requirements": {
          "levelMin": 50
        },
        "monsterTasks": [
          {
            "monsterId": 215,
            "amount": 600
          }
        ],
        "rewards": [
          {
            "amount": 15000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 11,
        "title": "Paw and Fur II - Bonebeast",
        "description": "Derrote 700 Bonebeasts.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 49,
            "amount": 700
          }
        ],
        "rewards": [
          {
            "amount": 15000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 12,
        "title": "Paw and Fur II - Crystal Spider",
        "description": "Derrote 700 Crystal Spiders.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 201,
            "amount": 700
          }
        ],
        "rewards": [
          {
            "amount": 15000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 13,
        "title": "Paw and Fur II - Ice Golem",
        "description": "Derrote 700 Ice Golems.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 202,
            "amount": 700
          }
        ],
        "rewards": [
          {
            "amount": 15000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 14,
        "title": "Paw and Fur II - Killer Caiman",
        "description": "Derrote 600 Killer Caimans.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 216,
            "amount": 600
          }
        ],
        "rewards": [
          {
            "amount": 15000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 15,
        "title": "Paw and Fur II - Mutated Rat",
        "description": "Derrote 900 Mutated Rats.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 58,
            "amount": 900
          }
        ],
        "rewards": [
          {
            "amount": 15000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 16,
        "title": "Paw and Fur II - Mutated Tiger",
        "description": "Derrote 600 Mutated Tigers.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 60,
            "amount": 600
          }
        ],
        "rewards": [
          {
            "amount": 15000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 17,
        "title": "Paw and Fur II - Crystal Spider II",
        "description": "Derrote mais 1000 Crystal Spiders.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 201,
            "amount": 1000
          }
        ],
        "rewards": [
          {
            "amount": 15000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 18,
        "title": "Paw and Fur II - Mutated Tiger II",
        "description": "Derrote mais 900 Mutated Tigers.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 60,
            "amount": 900
          }
        ],
        "rewards": [
          {
            "amount": 15000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 19,
        "title": "Paw and Fur II - Ancient Scarab II",
        "description": "Derrote mais 900 Ancient Scarabs.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 215,
            "amount": 900
          }
        ],
        "rewards": [
          {
            "amount": 15000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 20,
        "title": "Paw and Fur II - Bonebeast II",
        "description": "Derrote mais 1000 Bonebeasts.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 49,
            "amount": 1000
          }
        ],
        "rewards": [
          {
            "amount": 15000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 21,
        "title": "Paw and Fur II - Ice Golem II",
        "description": "Derrote mais 1000 Ice Golems.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 202,
            "amount": 1000
          }
        ],
        "rewards": [
          {
            "amount": 15000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 22,
        "title": "Paw and Fur II - Killer Caiman II",
        "description": "Derrote mais 900 Killer Caimans para alcançar 50 Hunting Points e liberar a Paw and Fur III.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 216,
            "amount": 900
          }
        ],
        "rewards": [
          {
            "amount": 15000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 23,
        "title": "Paw and Fur III - Brimstone Bug",
        "description": "A Paw and Fur III foi liberada. Derrote 1000 Brimstone Bugs para iniciar a terceira categoria.",
        "type": "monster_task",
        "requirements": {
          "levelMin": 80
        },
        "monsterTasks": [
          {
            "monsterId": 217,
            "amount": 1000
          }
        ],
        "rewards": [
          {
            "amount": 30000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 24,
        "title": "Paw and Fur III - Giant Spider",
        "description": "Derrote 1000 Giant Spiders.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 40,
            "amount": 1000
          }
        ],
        "rewards": [
          {
            "amount": 30000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 25,
        "title": "Paw and Fur III - Hellspawn",
        "description": "Derrote 1200 Hellspawns.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 222,
            "amount": 1200
          }
        ],
        "rewards": [
          {
            "amount": 30000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 26,
        "title": "Paw and Fur III - High Class Lizards",
        "description": "Derrote a elite dos lizards em Zao: Lizard High Guards, Lizard Legionnaires e Lizard Dragon Priests.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 231,
            "amount": 800
          },
          {
            "monsterId": 221,
            "amount": 800
          },
          {
            "monsterId": 229,
            "amount": 900
          }
        ],
        "rewards": [
          {
            "amount": 30000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 27,
        "title": "Paw and Fur III - Mutated Bat",
        "description": "Derrote 800 Mutated Bats.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 59,
            "amount": 800
          }
        ],
        "rewards": [
          {
            "amount": 30000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 28,
        "title": "Paw and Fur III - Nightmare",
        "description": "Derrote 800 Nightmares.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 192,
            "amount": 800
          }
        ],
        "rewards": [
          {
            "amount": 30000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 29,
        "title": "Paw and Fur III - Werewolf",
        "description": "Derrote 700 Werewolves.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 79,
            "amount": 700
          }
        ],
        "rewards": [
          {
            "amount": 30000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 30,
        "title": "Paw and Fur III - Hellspawn II",
        "description": "Derrote mais 1600 Hellspawns.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 222,
            "amount": 1600
          }
        ],
        "rewards": [
          {
            "amount": 30000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 31,
        "title": "Paw and Fur III - Werewolf II",
        "description": "Derrote mais 1000 Werewolves.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 79,
            "amount": 1000
          }
        ],
        "rewards": [
          {
            "amount": 30000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 32,
        "title": "Paw and Fur III - Brimstone Bug II",
        "description": "Derrote mais 1400 Brimstone Bugs.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 217,
            "amount": 1400
          }
        ],
        "rewards": [
          {
            "amount": 30000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 33,
        "title": "Paw and Fur III - Giant Spider II",
        "description": "Derrote mais 1400 Giant Spiders.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 40,
            "amount": 1400
          }
        ],
        "rewards": [
          {
            "amount": 30000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 34,
        "title": "Paw and Fur III - Nightmare II",
        "description": "Derrote mais 1100 Nightmares.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 192,
            "amount": 1100
          }
        ],
        "rewards": [
          {
            "amount": 30000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 35,
        "title": "Paw and Fur III - High Class Lizards II",
        "description": "Derrote novamente a elite dos lizards em uma caçada ainda maior.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 231,
            "amount": 1000
          },
          {
            "monsterId": 221,
            "amount": 1000
          },
          {
            "monsterId": 229,
            "amount": 1100
          }
        ],
        "rewards": [
          {
            "amount": 30000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 36,
        "title": "Paw and Fur III - Hellspawn III",
        "description": "Derrote mais 2000 Hellspawns.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 222,
            "amount": 2000
          }
        ],
        "rewards": [
          {
            "amount": 30000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 37,
        "title": "Paw and Fur III - Werewolf III",
        "description": "Derrote mais 1400 Werewolves para alcançar 100 Hunting Points, liberar o desafio Demodras e desbloquear a Paw and Fur IV.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 79,
            "amount": 1400
          }
        ],
        "rewards": [
          {
            "amount": 30000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 38,
        "title": "Paw and Fur IV - Behemoth",
        "description": "A Paw and Fur IV foi liberada. Derrote 1200 Behemoths para iniciar a categoria final.",
        "type": "monster_task",
        "requirements": {
          "levelMin": 130
        },
        "monsterTasks": [
          {
            "monsterId": 224,
            "amount": 1200
          }
        ],
        "rewards": [
          {
            "amount": 60000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 39,
        "title": "Paw and Fur IV - Drakens",
        "description": "Derrote Drakens em Zao: Draken Warmasters, Draken Spellweavers e Draken Elites.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 82,
            "amount": 1100
          },
          {
            "monsterId": 83,
            "amount": 1100
          },
          {
            "monsterId": 87,
            "amount": 1100
          }
        ],
        "rewards": [
          {
            "amount": 60000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 40,
        "title": "Paw and Fur IV - Ghastly Dragon",
        "description": "Derrote 1000 Ghastly Dragons.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 84,
            "amount": 1000
          }
        ],
        "rewards": [
          {
            "amount": 60000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 41,
        "title": "Paw and Fur IV - Hydra",
        "description": "Derrote 1400 Hydras.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 36,
            "amount": 1400
          }
        ],
        "rewards": [
          {
            "amount": 60000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 42,
        "title": "Paw and Fur IV - Medusa",
        "description": "Derrote 1000 Medusas.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 142,
            "amount": 1000
          }
        ],
        "rewards": [
          {
            "amount": 60000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 43,
        "title": "Paw and Fur IV - Sea Serpent",
        "description": "Derrote Sea Serpents e Young Sea Serpents nas profundezas marítimas.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 225,
            "amount": 1200
          },
          {
            "monsterId": 226,
            "amount": 600
          }
        ],
        "rewards": [
          {
            "amount": 60000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 44,
        "title": "Paw and Fur IV - Serpent Spawn",
        "description": "Derrote 1200 Serpent Spawns.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 143,
            "amount": 1200
          }
        ],
        "rewards": [
          {
            "amount": 60000,
            "type": "gold",
            "id": "gold"
          }
        ]
      },
      {
        "id": 45,
        "title": "Paw and Fur IV - Behemoth II",
        "description": "Derrote mais 1600 Behemoths para concluir a Paw and Fur IV e liberar o desafio 66666 Demons.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 224,
            "amount": 1600
          }
        ],
        "rewards": [
          {
            "amount": 60000,
            "type": "gold",
            "id": "gold"
          }
        ]
      }
    ]
  },
  {
    "id": 7,
    "title": "The Demon Oak Quest",
    "description": "Os Ruthless Seven mandaram um poderoso demônio para Plains Of Havoc. Você tem o que é preciso para impedi-lo?",
    "levelMin": 120,
    "premium": true,
    "requiredQuestIds": [
      6
    ],
    "repeatPolicy": {
      "type": "never"
    },
    "rewardHighlight": {
      "itemId": 1270
    },
    "missions": [
      {
        "id": 1,
        "title": "Demon Task",
        "description": "Derrote 6666 Demons",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 1,
            "amount": 6666
          }
        ]
      },
      {
        "id": 2,
        "title": "The Demon Oak",
        "description": "Derrote The Demon Oak",
        "type": "current_hunt",
        "rooms": [
          {
            "id": 1,
            "mapId": 192,
            "title": "The Demon Oak",
            "waves": [
              {
                "monsterIds": [
                  298,
                  49,
                  181
                ],
                "minMonsters": 6,
                "maxMonsters": 6
              },
              {
                "monsterIds": [
                  178,
                  183,
                  182
                ],
                "minMonsters": 5,
                "maxMonsters": 5
              },
              {
                "monsterIds": [
                  180,
                  241
                ],
                "minMonsters": 4,
                "maxMonsters": 4
              },
              {
                "monsterIds": [
                  40,
                  178,
                  197,
                  187
                ],
                "minMonsters": 5,
                "maxMonsters": 5
              }
            ],
            "ambientLight": 1
          }
        ],
        "rewardChoices": [
          {
            "id": "demon-legs",
            "label": "Demon Legs",
            "rewards": [
              {
                "id": "choice-demon-legs",
                "type": "item",
                "amount": 1,
                "itemId": 1270
              }
            ]
          },
          {
            "id": "rainbow-shield",
            "label": "Rainbow Shield",
            "rewards": [
              {
                "id": "choice-rainbow-shield",
                "type": "item",
                "amount": 1,
                "itemId": 1271
              }
            ]
          },
          {
            "id": "spellbook",
            "label": "Spellbook Of Ancient Arcana",
            "rewards": [
              {
                "id": "choice-spellbook",
                "type": "item",
                "amount": 1,
                "itemId": 1272
              }
            ]
          },
          {
            "id": "thorn-spitter",
            "label": "Thorn Spitter",
            "rewards": [
              {
                "id": "choice-thorn-spitter",
                "type": "item",
                "amount": 1,
                "itemId": 1273
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "id": 8,
    "title": "Ice Islands I",
    "description": "As regiões mais externas das Ice Islands são habitadas por caçadores, contrabandistas e aventureiros que tentam sobreviver ao frio extremo. Rumores falam sobre antigas ruínas escondidas sob a neve, mas poucos se arriscam a investigar.",
    "levelMin": 20,
    "premium": false,
    "unlockedByDefault": true,
    "repeatPolicy": {
      "type": "never"
    },
    "rewardHighlight": {
      "itemId": 38
    },
    "missions": [
      {
        "id": 1,
        "title": "Explorando as Ice Islands",
        "description": "Cace as criaturas das regiões externas das Ice Islands para provar que está preparado para investigar as ruínas escondidas sob a neve.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 311,
            "amount": 100
          },
          {
            "monsterId": 310,
            "amount": 100
          },
          {
            "monsterId": 314,
            "amount": 50
          }
        ]
      },
      {
        "id": 2,
        "title": "Ruínas Congeladas",
        "description": "Após sobreviver às primeiras caçadas nas Ice Islands, avance pela costa congelada, investigue o acampamento abandonado dos caçadores e explore o antigo templo nórdico escondido sob a neve.",
        "type": "current_hunt",
        "rewards": [
          {
            "id": "unlock-barbarian-hunts",
            "type": "unlock_hunt",
            "huntId": 119
          },
          {
            "id": "life-ring",
            "type": "item",
            "amount": 1,
            "itemId": 38
          }
        ],
        "rooms": [
          {
            "id": 1,
            "title": "Costa Congelada",
            "mapId": 207,
            "ambientLight": 0.8,
            "waves": [
              {
                "minMonsters": 4,
                "maxMonsters": 6,
                "waveAmount": 2,
                "monsterIds": [
                  312,
                  319
                ]
              },
              {
                "minMonsters": 5,
                "maxMonsters": 7,
                "waveAmount": 2,
                "monsterIds": [
                  312,
                  319,
                  320
                ]
              },
              {
                "minMonsters": 6,
                "maxMonsters": 8,
                "waveAmount": 1,
                "monsterIds": [
                  319,
                  320
                ]
              }
            ]
          },
          {
            "id": 2,
            "title": "Acampamento dos Caçadores",
            "mapId": 208,
            "ambientLight": 0.75,
            "waves": [
              {
                "minMonsters": 5,
                "maxMonsters": 7,
                "waveAmount": 2,
                "monsterIds": [
                  319,
                  320
                ]
              },
              {
                "minMonsters": 6,
                "maxMonsters": 8,
                "waveAmount": 2,
                "monsterIds": [
                  319,
                  320,
                  321
                ]
              },
              {
                "minMonsters": 7,
                "maxMonsters": 8,
                "waveAmount": 1,
                "monsterIds": [
                  320,
                  321
                ]
              }
            ]
          },
          {
            "id": 3,
            "title": "Templo Nórdico",
            "mapId": 209,
            "ambientLight": 0.65,
            "waves": [
              {
                "minMonsters": 5,
                "maxMonsters": 7,
                "waveAmount": 2,
                "monsterIds": [
                  321,
                  320
                ]
              },
              {
                "minMonsters": 6,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  321,
                  320,
                  10
                ]
              },
              {
                "minMonsters": 7,
                "maxMonsters": 8,
                "waveAmount": 4,
                "monsterIds": [
                  321,
                  10
                ]
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "id": 9,
    "title": "Ice Islands II",
    "description": "As pistas encontradas no templo apontam para antigas tribos bárbaras que dominavam o interior das Ice Islands. Porém, algo mais sombrio parece ter se infiltrado entre elas.",
    "levelMin": 35,
    "premium": true,
    "requiredQuestIds": [
      8
    ],
    "repeatPolicy": {
      "type": "never"
    },
    "rewardHighlight": {
      "itemId": 1353
    },
    "missions": [
      {
        "id": 1,
        "title": "Vila dos Bárbaros",
        "description": "As tribos bárbaras ainda dominam parte das Ice Islands. Derrote seus guerreiros para conseguir avançar até as fortalezas do norte.",
        "type": "monster_task",
        "monsterTasks": [
          {
            "monsterId": 316,
            "amount": 150
          },
          {
            "monsterId": 317,
            "amount": 150
          },
          {
            "monsterId": 318,
            "amount": 150
          }
        ]
      },
      {
        "id": 2,
        "title": "Culto nas Ice Islands",
        "description": "Após enfrentar as tribos bárbaras, avance pela fortaleza tomada, descubra o santuário escondido dos cultistas e purifique os campos corrompidos pelos rituais proibidos.",
        "type": "current_hunt",
        "rewards": [
          {
            "id": "fur-boots",
            "type": "item",
            "itemId": 1353,
            "amount": 1
          },
          {
            "id": "unlock-frost-giant-hunt",
            "type": "unlock_hunt",
            "huntId": 120
          }
        ],
        "rooms": [
          {
            "id": 1,
            "title": "Fortaleza Bárbara",
            "mapId": 211,
            "ambientLight": 0.7,
            "waves": [
              {
                "minMonsters": 4,
                "maxMonsters": 6,
                "waveAmount": 2,
                "monsterIds": [
                  322,
                  247
                ]
              },
              {
                "minMonsters": 5,
                "maxMonsters": 7,
                "waveAmount": 2,
                "monsterIds": [
                  322,
                  247
                ]
              },
              {
                "minMonsters": 6,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  322,
                  247
                ]
              },
              {
                "minMonsters": 7,
                "maxMonsters": 8,
                "waveAmount": 4,
                "monsterIds": [
                  322,
                  247
                ]
              }
            ]
          },
          {
            "id": 2,
            "title": "Santuário dos Cultistas",
            "mapId": 217,
            "ambientLight": 0.55,
            "waves": [
              {
                "minMonsters": 4,
                "maxMonsters": 6,
                "waveAmount": 2,
                "monsterIds": [
                  247,
                  248
                ]
              },
              {
                "minMonsters": 5,
                "maxMonsters": 7,
                "waveAmount": 2,
                "monsterIds": [
                  247,
                  248
                ]
              },
              {
                "minMonsters": 6,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  247,
                  248
                ]
              },
              {
                "minMonsters": 7,
                "maxMonsters": 8,
                "waveAmount": 4,
                "monsterIds": [
                  248,
                  247
                ]
              }
            ]
          },
          {
            "id": 3,
            "title": "Campos Profanados",
            "mapId": 213,
            "ambientLight": 0.6,
            "waves": [
              {
                "minMonsters": 5,
                "maxMonsters": 7,
                "waveAmount": 2,
                "monsterIds": [
                  322,
                  250
                ]
              },
              {
                "minMonsters": 6,
                "maxMonsters": 8,
                "waveAmount": 2,
                "monsterIds": [
                  322,
                  248,
                  250
                ]
              },
              {
                "minMonsters": 7,
                "maxMonsters": 8,
                "waveAmount": 3,
                "monsterIds": [
                  248,
                  250,
                  322
                ]
              },
              {
                "minMonsters": 8,
                "maxMonsters": 8,
                "waveAmount": 4,
                "monsterIds": [
                  248,
                  250,
                  322
                ]
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "id": 10,
    "title": "Barbarian Arena - Greenhorn",
    "description": "A primeira dificuldade da arena de Svargrond coloca o competidor contra dez chefes em sequência, em combates diretos e sem loot.",
    "levelMin": 35,
    "premium": true,
    "requiredQuestIds": [
      9
    ],
    "repeatPolicy": {
      "type": "never"
    },
    "rewardHighlight": {
      "itemId": 1431
    },
    "missions": [
      {
        "id": 1,
        "title": "Greenhorn Arena",
        "description": "Pague a taxa de entrada e derrote os dez chefes da modalidade Greenhorn para escolher seu prêmio.",
        "type": "current_hunt",
        "deliveryGold": 1000,
        "minPlayers": 1,
        "maxPlayers": 1,
        "rewards": [
          {
            "id": "goblet",
            "amount": 1,
            "type": "item",
            "itemId": 1431
          }
        ],
        "rewardChoices": [
          {
            "id": "orcish-maul",
            "label": "Orcish Maul",
            "rewards": [
              {
                "id": "choice-orcish-maul",
                "type": "item",
                "amount": 1,
                "itemId": 222
              }
            ]
          },
          {
            "id": "headchopper",
            "label": "Headchopper",
            "rewards": [
              {
                "id": "choice-headchopper",
                "type": "item",
                "amount": 1,
                "itemId": 223
              }
            ]
          },
          {
            "id": "blacksteel-sword",
            "label": "Blacksteel Sword",
            "rewards": [
              {
                "id": "choice-blacksteel-sword",
                "type": "item",
                "amount": 1,
                "itemId": 224
              }
            ]
          }
        ],
        "rooms": [
          {
            "id": 1,
            "title": "Frostfur",
            "mapId": 203,
            "waves": [
              {
                "monsterIds": [
                  338
                ],
                "minMonsters": 1,
                "maxMonsters": 1,
                "waveAmount": 1
              }
            ]
          },
          {
            "id": 2,
            "title": "Bloodpaw",
            "mapId": 203,
            "waves": [
              {
                "monsterIds": [
                  339
                ],
                "minMonsters": 1,
                "maxMonsters": 1,
                "waveAmount": 1
              }
            ]
          },
          {
            "id": 3,
            "title": "Bovinus",
            "mapId": 203,
            "waves": [
              {
                "monsterIds": [
                  340
                ],
                "minMonsters": 1,
                "maxMonsters": 1,
                "waveAmount": 1
              }
            ]
          },
          {
            "id": 4,
            "title": "Achad",
            "mapId": 203,
            "waves": [
              {
                "monsterIds": [
                  341
                ],
                "minMonsters": 1,
                "maxMonsters": 1,
                "waveAmount": 1
              }
            ]
          },
          {
            "id": 5,
            "title": "Colerian the Barbarian",
            "mapId": 203,
            "waves": [
              {
                "monsterIds": [
                  342
                ],
                "minMonsters": 1,
                "maxMonsters": 1,
                "waveAmount": 1
              }
            ]
          },
          {
            "id": 6,
            "title": "The Hairy One",
            "mapId": 203,
            "waves": [
              {
                "monsterIds": [
                  343
                ],
                "minMonsters": 1,
                "maxMonsters": 1,
                "waveAmount": 1
              }
            ]
          },
          {
            "id": 7,
            "title": "Axeitus Headbanger",
            "mapId": 203,
            "waves": [
              {
                "monsterIds": [
                  344
                ],
                "minMonsters": 1,
                "maxMonsters": 1,
                "waveAmount": 1
              }
            ]
          },
          {
            "id": 8,
            "title": "Rocky",
            "mapId": 203,
            "waves": [
              {
                "monsterIds": [
                  50
                ],
                "minMonsters": 1,
                "maxMonsters": 1,
                "waveAmount": 1
              }
            ]
          },
          {
            "id": 9,
            "title": "Cursed Gladiator",
            "mapId": 203,
            "waves": [
              {
                "monsterIds": [
                  51
                ],
                "minMonsters": 1,
                "maxMonsters": 1,
                "waveAmount": 1
              }
            ]
          },
          {
            "id": 10,
            "title": "Orcus the Cruel",
            "mapId": 203,
            "waves": [
              {
                "monsterIds": [
                  52
                ],
                "minMonsters": 1,
                "maxMonsters": 1,
                "waveAmount": 1
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "id": 11,
    "title": "Barbarian Arena - Scrapper",
    "description": "A modalidade intermediária da arena de Svargrond exige vencer dez chefes mais perigosos em sequência.",
    "levelMin": 35,
    "premium": true,
    "requiredQuestIds": [
      10
    ],
    "repeatPolicy": {
      "type": "never"
    },
    "rewardHighlight": {
      "itemId": 1011
    },
    "missions": [
      {
        "id": 1,
        "title": "Scrapper Arena",
        "description": "Pague a taxa de entrada e derrote os dez chefes da modalidade Scrapper para escolher seu prêmio.",
        "type": "current_hunt",
        "deliveryGold": 5000,
        "minPlayers": 1,
        "maxPlayers": 1,
        "rewards": [
          {
            "id": "goblet",
            "amount": 1,
            "type": "item",
            "itemId": 1011
          }
        ],
        "rewardChoices": [
          {
            "id": "cranial-basher",
            "label": "Cranial Basher",
            "rewards": [
              {
                "id": "choice-cranial-basher",
                "type": "item",
                "amount": 1,
                "itemId": 1433
              }
            ]
          },
          {
            "id": "heroic-axe",
            "label": "Heroic Axe",
            "rewards": [
              {
                "id": "choice-heroic-axe",
                "type": "item",
                "amount": 1,
                "itemId": 1434
              }
            ]
          },
          {
            "id": "mystic-blade",
            "label": "Mystic Blade",
            "rewards": [
              {
                "id": "choice-mystic-blade",
                "type": "item",
                "amount": 1,
                "itemId": 1435
              }
            ]
          },
          {
            "id": "present-box",
            "label": "Present Box",
            "rewards": [
              {
                "id": "choice-baby-seal-doll",
                "type": "item",
                "amount": 1,
                "itemId": 1442
              },
              {
                "id": "choice-bar-of-chocolate",
                "type": "item",
                "amount": 1,
                "itemId": 1072
              },
              {
                "id": "choice-ice-cream-cone",
                "type": "item",
                "amount": 1,
                "itemId": 1441
              },
              {
                "id": "choice-candy",
                "type": "item",
                "amount": 10,
                "itemId": 1440
              }
            ]
          }
        ],
        "rooms": [
          {
            "id": 1,
            "title": "Avalanche",
            "mapId": 203,
            "waves": [
              {
                "monsterIds": [
                  345
                ],
                "minMonsters": 1,
                "maxMonsters": 1,
                "waveAmount": 1
              }
            ]
          },
          {
            "id": 2,
            "title": "Kreebosh the Exile",
            "mapId": 203,
            "waves": [
              {
                "monsterIds": [
                  346
                ],
                "minMonsters": 1,
                "maxMonsters": 1,
                "waveAmount": 1
              }
            ]
          },
          {
            "id": 3,
            "title": "The Dark Dancer",
            "mapId": 203,
            "waves": [
              {
                "monsterIds": [
                  348
                ],
                "minMonsters": 1,
                "maxMonsters": 1,
                "waveAmount": 1
              }
            ]
          },
          {
            "id": 4,
            "title": "The Hag",
            "mapId": 203,
            "waves": [
              {
                "monsterIds": [
                  349
                ],
                "minMonsters": 1,
                "maxMonsters": 1,
                "waveAmount": 1
              }
            ]
          },
          {
            "id": 5,
            "title": "Slim",
            "mapId": 203,
            "waves": [
              {
                "monsterIds": [
                  350
                ],
                "minMonsters": 1,
                "maxMonsters": 1,
                "waveAmount": 1
              }
            ]
          },
          {
            "id": 6,
            "title": "Grimgor Guteater",
            "mapId": 203,
            "waves": [
              {
                "monsterIds": [
                  351
                ],
                "minMonsters": 1,
                "maxMonsters": 1,
                "waveAmount": 1
              }
            ]
          },
          {
            "id": 7,
            "title": "Drasilla",
            "mapId": 203,
            "waves": [
              {
                "monsterIds": [
                  352
                ],
                "minMonsters": 1,
                "maxMonsters": 1,
                "waveAmount": 1
              }
            ]
          },
          {
            "id": 8,
            "title": "Spirit of Earth",
            "mapId": 203,
            "waves": [
              {
                "monsterIds": [
                  353
                ],
                "minMonsters": 1,
                "maxMonsters": 1,
                "waveAmount": 1
              }
            ]
          },
          {
            "id": 9,
            "title": "Spirit of Water",
            "mapId": 203,
            "waves": [
              {
                "monsterIds": [
                  354
                ],
                "minMonsters": 1,
                "maxMonsters": 1,
                "waveAmount": 1
              }
            ]
          },
          {
            "id": 10,
            "title": "Spirit of Fire",
            "mapId": 203,
            "waves": [
              {
                "monsterIds": [
                  355
                ],
                "minMonsters": 1,
                "maxMonsters": 1,
                "waveAmount": 1
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "id": 12,
    "title": "Barbarian Arena - Warlord",
    "description": "A modalidade final da arena de Svargrond reúne os dez chefes mais fortes do desafio bárbaro.",
    "levelMin": 35,
    "premium": true,
    "requiredQuestIds": [
      11
    ],
    "repeatPolicy": {
      "type": "never"
    },
    "rewardHighlight": {
      "itemId": 1432
    },
    "missions": [
      {
        "id": 1,
        "title": "Warlord Arena",
        "description": "Pague a taxa de entrada e derrote os dez chefes da modalidade Warlord para escolher seu prêmio.",
        "type": "current_hunt",
        "deliveryGold": 10000,
        "minPlayers": 1,
        "maxPlayers": 1,
        "rewards": [
          {
            "id": "goblet",
            "amount": 1,
            "type": "item",
            "itemId": 1432
          }
        ],
        "rewardChoices": [
          {
            "id": "blessed-sceptre",
            "label": "Blessed Sceptre",
            "rewards": [
              {
                "id": "choice-blessed-sceptre",
                "type": "item",
                "amount": 1,
                "itemId": 1436
              }
            ]
          },
          {
            "id": "royal-axe",
            "label": "Royal Axe",
            "rewards": [
              {
                "id": "choice-royal-axe",
                "type": "item",
                "amount": 1,
                "itemId": 1437
              }
            ]
          },
          {
            "id": "justice-seeker",
            "label": "Justice Seeker",
            "rewards": [
              {
                "id": "choice-justice-seeker",
                "type": "item",
                "amount": 1,
                "itemId": 1438
              }
            ]
          },
          {
            "id": "present-box",
            "label": "Present Box",
            "rewards": [
              {
                "id": "choice-panda-teddy",
                "type": "item",
                "amount": 1,
                "itemId": 1446
              },
              {
                "id": "choice-bar-of-chocolate",
                "type": "item",
                "amount": 1,
                "itemId": 1072
              },
              {
                "id": "choice-ice-cream-cone",
                "type": "item",
                "amount": 1,
                "itemId": 1441
              },
              {
                "id": "choice-candy",
                "type": "item",
                "amount": 10,
                "itemId": 1440
              }
            ]
          }
        ],
        "rooms": [
          {
            "id": 1,
            "title": "Webster",
            "mapId": 203,
            "waves": [
              {
                "monsterIds": [
                  356
                ],
                "minMonsters": 1,
                "maxMonsters": 1,
                "waveAmount": 1
              }
            ]
          },
          {
            "id": 2,
            "title": "Darakan the Executioner",
            "mapId": 203,
            "waves": [
              {
                "monsterIds": [
                  357
                ],
                "minMonsters": 1,
                "maxMonsters": 1,
                "waveAmount": 1
              }
            ]
          },
          {
            "id": 3,
            "title": "Norgle Glacierbeard",
            "mapId": 203,
            "waves": [
              {
                "monsterIds": [
                  358
                ],
                "minMonsters": 1,
                "maxMonsters": 1,
                "waveAmount": 1
              }
            ]
          },
          {
            "id": 4,
            "title": "The Pit Lord",
            "mapId": 203,
            "waves": [
              {
                "monsterIds": [
                  359
                ],
                "minMonsters": 1,
                "maxMonsters": 1,
                "waveAmount": 1
              }
            ]
          },
          {
            "id": 5,
            "title": "Svoren the Mad",
            "mapId": 203,
            "waves": [
              {
                "monsterIds": [
                  360
                ],
                "minMonsters": 1,
                "maxMonsters": 1,
                "waveAmount": 1
              }
            ]
          },
          {
            "id": 6,
            "title": "The Masked Marauder",
            "mapId": 203,
            "waves": [
              {
                "monsterIds": [
                  361
                ],
                "minMonsters": 1,
                "maxMonsters": 1,
                "waveAmount": 1
              }
            ]
          },
          {
            "id": 7,
            "title": "Gnorre Chyllson",
            "mapId": 203,
            "waves": [
              {
                "monsterIds": [
                  362
                ],
                "minMonsters": 1,
                "maxMonsters": 1,
                "waveAmount": 1
              }
            ]
          },
          {
            "id": 8,
            "title": "Fallen Mooh'tah Master Ghar",
            "mapId": 203,
            "waves": [
              {
                "monsterIds": [
                  363
                ],
                "minMonsters": 1,
                "maxMonsters": 1,
                "waveAmount": 1
              }
            ]
          },
          {
            "id": 9,
            "title": "Deathbringer",
            "mapId": 203,
            "waves": [
              {
                "monsterIds": [
                  364
                ],
                "minMonsters": 1,
                "maxMonsters": 1,
                "waveAmount": 1
              }
            ]
          },
          {
            "id": 10,
            "title": "The Obliverator",
            "mapId": 203,
            "waves": [
              {
                "monsterIds": [
                  365
                ],
                "minMonsters": 1,
                "maxMonsters": 1,
                "waveAmount": 1
              }
            ]
          }
        ]
      }
    ]
  }
];
