// Auto-generated by scripts/generate-game-data.mjs
// Do not edit manually. Run: bun run generate:game-data
// Generated at: 2026-07-15T02:47:45.897Z
// Game data version: 79323581daae3bb1
// Static data version: a9a9d3105392ff90
// Source bundle: https://stonegy-online.com/_next/static/chunks/pages/_app-f431d076605ee183.js

export const ENCHANT = [
  {
    "id": 3001,
    "label": "Werewolf Amulet",
    "sourceItemId": 26,
    "resultItemId": 449,
    "costs": [
      {
        "itemId": 336,
        "amount": 1
      }
    ],
    "blocksMarketResult": true
  },
  {
    "id": 3002,
    "label": "Soft Boots Repair",
    "sourceItemId": 1019,
    "resultItemId": 972,
    "costs": [],
    "goldCost": 10000
  },
  {
    "id": 3003,
    "label": "Amulet of Theurgy",
    "sourceItemId": 1133,
    "resultItemId": 1134,
    "costs": [
      {
        "itemId": 541,
        "amount": 2
      }
    ]
  },
  {
    "id": 3004,
    "label": "Blister Ring",
    "sourceItemId": 1129,
    "resultItemId": 1130,
    "costs": [
      {
        "itemId": 541,
        "amount": 2
      }
    ]
  }
];
