// Auto-generated by scripts/generate-game-data.mjs
// Do not edit manually. Run: bun run generate:game-data
// Generated at: 2026-07-14T18:24:08.836Z
// Game data version: 79323581daae3bb1
// Static data version: a9a9d3105392ff90
// Source bundle: https://stonegy-online.com/_next/static/chunks/pages/_app-f431d076605ee183.js

export const IMBUEMENTS = [
  {
    "id": "basic_strike",
    "name": "Basic Strike",
    "tier": "BASIC",
    "category": "CRITICAL",
    "icon": "/assets/ui/imbuements/strike.gif",
    "description": "Adds 10% critical chance and 15% extra critical damage.",
    "durationMs": 72000000,
    "goldFee": 5000,
    "protectionGoldFee": 10000,
    "successRate": 90,
    "premiumOnly": false,
    "ingredients": [
      {
        "itemName": "Protective Charm",
        "amount": 20
      }
    ]
  },
  {
    "id": "intricate_strike",
    "name": "Intricate Strike",
    "tier": "INTRICATE",
    "category": "CRITICAL",
    "icon": "/assets/ui/imbuements/strike.gif",
    "description": "Adds 10% critical chance and 25% extra critical damage.",
    "durationMs": 72000000,
    "goldFee": 30000,
    "protectionGoldFee": 30000,
    "successRate": 70,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Protective Charm",
        "amount": 20
      },
      {
        "itemName": "Sabretooth",
        "amount": 25
      }
    ]
  },
  {
    "id": "powerful_strike",
    "name": "Powerful Strike",
    "tier": "POWERFUL",
    "category": "CRITICAL",
    "icon": "/assets/ui/imbuements/strike.gif",
    "description": "Adds 10% critical chance and 50% extra critical damage.",
    "durationMs": 72000000,
    "goldFee": 200000,
    "protectionGoldFee": 50000,
    "successRate": 50,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Protective Charm",
        "amount": 20
      },
      {
        "itemName": "Sabretooth",
        "amount": 25
      },
      {
        "itemName": "Vexclaw Talon",
        "amount": 5
      }
    ]
  },
  {
    "id": "basic_reap",
    "name": "Basic Reap",
    "tier": "BASIC",
    "category": "ELEMENTAL_DEATH",
    "icon": "/assets/ui/imbuements/reap.gif",
    "description": "Converts 10% of physical damage to death damage.",
    "durationMs": 72000000,
    "goldFee": 5000,
    "protectionGoldFee": 10000,
    "successRate": 90,
    "premiumOnly": false,
    "ingredients": [
      {
        "itemName": "Pile Of Grave Earth",
        "amount": 25
      }
    ]
  },
  {
    "id": "intricate_reap",
    "name": "Intricate Reap",
    "tier": "INTRICATE",
    "category": "ELEMENTAL_DEATH",
    "icon": "/assets/ui/imbuements/reap.gif",
    "description": "Converts 25% of physical damage to death damage.",
    "durationMs": 72000000,
    "goldFee": 30000,
    "protectionGoldFee": 30000,
    "successRate": 70,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Pile Of Grave Earth",
        "amount": 25
      },
      {
        "itemName": "Demonic Skeletal Hand",
        "amount": 20
      }
    ]
  },
  {
    "id": "powerful_reap",
    "name": "Powerful Reap",
    "tier": "POWERFUL",
    "category": "ELEMENTAL_DEATH",
    "icon": "/assets/ui/imbuements/reap.gif",
    "description": "Converts 50% of physical damage to death damage.",
    "durationMs": 72000000,
    "goldFee": 200000,
    "protectionGoldFee": 50000,
    "successRate": 50,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Pile Of Grave Earth",
        "amount": 25
      },
      {
        "itemName": "Demonic Skeletal Hand",
        "amount": 20
      },
      {
        "itemName": "Petrified Scream",
        "amount": 5
      }
    ]
  },
  {
    "id": "basic_venom",
    "name": "Basic Venom",
    "tier": "BASIC",
    "category": "ELEMENTAL_EARTH",
    "icon": "/assets/ui/imbuements/venom.gif",
    "description": "Converts 10% of physical damage to earth damage.",
    "durationMs": 72000000,
    "goldFee": 5000,
    "protectionGoldFee": 10000,
    "successRate": 90,
    "premiumOnly": false,
    "ingredients": [
      {
        "itemName": "Swamp Grass",
        "amount": 25
      }
    ]
  },
  {
    "id": "intricate_venom",
    "name": "Intricate Venom",
    "tier": "INTRICATE",
    "category": "ELEMENTAL_EARTH",
    "icon": "/assets/ui/imbuements/venom.gif",
    "description": "Converts 25% of physical damage to earth damage.",
    "durationMs": 72000000,
    "goldFee": 30000,
    "protectionGoldFee": 30000,
    "successRate": 70,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Swamp Grass",
        "amount": 25
      },
      {
        "itemName": "Poisonous Slime",
        "amount": 20
      }
    ]
  },
  {
    "id": "powerful_venom",
    "name": "Powerful Venom",
    "tier": "POWERFUL",
    "category": "ELEMENTAL_EARTH",
    "icon": "/assets/ui/imbuements/venom.gif",
    "description": "Converts 50% of physical damage to earth damage.",
    "durationMs": 72000000,
    "goldFee": 200000,
    "protectionGoldFee": 50000,
    "successRate": 50,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Swamp Grass",
        "amount": 25
      },
      {
        "itemName": "Poisonous Slime",
        "amount": 20
      },
      {
        "itemName": "Slime Heart",
        "amount": 2
      }
    ]
  },
  {
    "id": "basic_electrify",
    "name": "Basic Electrify",
    "tier": "BASIC",
    "category": "ELEMENTAL_ENERGY",
    "icon": "/assets/ui/imbuements/electrify.gif",
    "description": "Converts 10% of physical damage to energy damage.",
    "durationMs": 72000000,
    "goldFee": 5000,
    "protectionGoldFee": 10000,
    "successRate": 90,
    "premiumOnly": false,
    "ingredients": [
      {
        "itemName": "Rorc Feather",
        "amount": 25
      }
    ]
  },
  {
    "id": "intricate_electrify",
    "name": "Intricate Electrify",
    "tier": "INTRICATE",
    "category": "ELEMENTAL_ENERGY",
    "icon": "/assets/ui/imbuements/electrify.gif",
    "description": "Converts 25% of physical damage to energy damage.",
    "durationMs": 72000000,
    "goldFee": 30000,
    "protectionGoldFee": 30000,
    "successRate": 70,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Rorc Feather",
        "amount": 25
      },
      {
        "itemName": "Peacock Feather Fan",
        "amount": 5
      }
    ]
  },
  {
    "id": "powerful_electrify",
    "name": "Powerful Electrify",
    "tier": "POWERFUL",
    "category": "ELEMENTAL_ENERGY",
    "icon": "/assets/ui/imbuements/electrify.gif",
    "description": "Converts 50% of physical damage to energy damage.",
    "durationMs": 72000000,
    "goldFee": 200000,
    "protectionGoldFee": 50000,
    "successRate": 50,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Rorc Feather",
        "amount": 25
      },
      {
        "itemName": "Peacock Feather Fan",
        "amount": 5
      },
      {
        "itemName": "Energy Vein",
        "amount": 1
      }
    ]
  },
  {
    "id": "basic_scorch",
    "name": "Basic Scorch",
    "tier": "BASIC",
    "category": "ELEMENTAL_FIRE",
    "icon": "/assets/ui/imbuements/scorch.gif",
    "description": "Converts 10% of physical damage to fire damage.",
    "durationMs": 72000000,
    "goldFee": 5000,
    "protectionGoldFee": 10000,
    "successRate": 90,
    "premiumOnly": false,
    "ingredients": [
      {
        "itemName": "Fiery Heart",
        "amount": 25
      }
    ]
  },
  {
    "id": "intricate_scorch",
    "name": "Intricate Scorch",
    "tier": "INTRICATE",
    "category": "ELEMENTAL_FIRE",
    "icon": "/assets/ui/imbuements/scorch.gif",
    "description": "Converts 25% of physical damage to fire damage.",
    "durationMs": 72000000,
    "goldFee": 30000,
    "protectionGoldFee": 30000,
    "successRate": 70,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Fiery Heart",
        "amount": 25
      },
      {
        "itemName": "Green Dragon Scale",
        "amount": 5
      }
    ]
  },
  {
    "id": "powerful_scorch",
    "name": "Powerful Scorch",
    "tier": "POWERFUL",
    "category": "ELEMENTAL_FIRE",
    "icon": "/assets/ui/imbuements/scorch.gif",
    "description": "Converts 50% of physical damage to fire damage.",
    "durationMs": 72000000,
    "goldFee": 200000,
    "protectionGoldFee": 50000,
    "successRate": 50,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Fiery Heart",
        "amount": 25
      },
      {
        "itemName": "Green Dragon Scale",
        "amount": 5
      },
      {
        "itemName": "Demon Horn",
        "amount": 5
      }
    ]
  },
  {
    "id": "basic_frost",
    "name": "Basic Frost",
    "tier": "BASIC",
    "category": "ELEMENTAL_ICE",
    "icon": "/assets/ui/imbuements/frost.gif",
    "description": "Converts 10% of physical damage to ice damage.",
    "durationMs": 72000000,
    "goldFee": 5000,
    "protectionGoldFee": 10000,
    "successRate": 90,
    "premiumOnly": false,
    "ingredients": [
      {
        "itemName": "Frosty Heart",
        "amount": 25
      }
    ]
  },
  {
    "id": "intricate_frost",
    "name": "Intricate Frost",
    "tier": "INTRICATE",
    "category": "ELEMENTAL_ICE",
    "icon": "/assets/ui/imbuements/frost.gif",
    "description": "Converts 25% of physical damage to ice damage.",
    "durationMs": 72000000,
    "goldFee": 30000,
    "protectionGoldFee": 30000,
    "successRate": 70,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Frosty Heart",
        "amount": 25
      },
      {
        "itemName": "Seacrest Hair",
        "amount": 10
      }
    ]
  },
  {
    "id": "powerful_frost",
    "name": "Powerful Frost",
    "tier": "POWERFUL",
    "category": "ELEMENTAL_ICE",
    "icon": "/assets/ui/imbuements/frost.gif",
    "description": "Converts 50% of physical damage to ice damage.",
    "durationMs": 72000000,
    "goldFee": 200000,
    "protectionGoldFee": 50000,
    "successRate": 50,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Frosty Heart",
        "amount": 25
      },
      {
        "itemName": "Seacrest Hair",
        "amount": 10
      },
      {
        "itemName": "Polar Bear Paw",
        "amount": 5
      }
    ]
  },
  {
    "id": "basic_vampirism",
    "name": "Basic Vampirism",
    "tier": "BASIC",
    "category": "LIFE_LEECH",
    "icon": "/assets/ui/imbuements/vampirism.gif",
    "description": "Converts 5% of inflicted damage into HP.",
    "durationMs": 72000000,
    "goldFee": 5000,
    "protectionGoldFee": 10000,
    "successRate": 90,
    "premiumOnly": false,
    "ingredients": [
      {
        "itemName": "Vampire Teeth",
        "amount": 25
      }
    ]
  },
  {
    "id": "intricate_vampirism",
    "name": "Intricate Vampirism",
    "tier": "INTRICATE",
    "category": "LIFE_LEECH",
    "icon": "/assets/ui/imbuements/vampirism.gif",
    "description": "Converts 10% of inflicted damage into HP.",
    "durationMs": 72000000,
    "goldFee": 30000,
    "protectionGoldFee": 30000,
    "successRate": 70,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Vampire Teeth",
        "amount": 25
      },
      {
        "itemName": "Bloody Pincers",
        "amount": 15
      }
    ]
  },
  {
    "id": "powerful_vampirism",
    "name": "Powerful Vampirism",
    "tier": "POWERFUL",
    "category": "LIFE_LEECH",
    "icon": "/assets/ui/imbuements/vampirism.gif",
    "description": "Converts 25% of inflicted damage into HP.",
    "durationMs": 72000000,
    "goldFee": 200000,
    "protectionGoldFee": 50000,
    "successRate": 50,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Vampire Teeth",
        "amount": 25
      },
      {
        "itemName": "Bloody Pincers",
        "amount": 15
      },
      {
        "itemName": "Piece of Dead Brain",
        "amount": 5
      }
    ]
  },
  {
    "id": "basic_void",
    "name": "Basic Void",
    "tier": "BASIC",
    "category": "MANA_LEECH",
    "icon": "/assets/ui/imbuements/void.gif",
    "description": "Converts 3% of inflicted damage into mana.",
    "durationMs": 72000000,
    "goldFee": 5000,
    "protectionGoldFee": 10000,
    "successRate": 90,
    "premiumOnly": false,
    "ingredients": [
      {
        "itemName": "Rope Belt",
        "amount": 25
      }
    ]
  },
  {
    "id": "intricate_void",
    "name": "Intricate Void",
    "tier": "INTRICATE",
    "category": "MANA_LEECH",
    "icon": "/assets/ui/imbuements/void.gif",
    "description": "Converts 5% of inflicted damage into mana.",
    "durationMs": 72000000,
    "goldFee": 30000,
    "protectionGoldFee": 30000,
    "successRate": 70,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Rope Belt",
        "amount": 25
      },
      {
        "itemName": "Silencer Claws",
        "amount": 25
      }
    ]
  },
  {
    "id": "powerful_void",
    "name": "Powerful Void",
    "tier": "POWERFUL",
    "category": "MANA_LEECH",
    "icon": "/assets/ui/imbuements/void.gif",
    "description": "Converts 8% of inflicted damage into mana.",
    "durationMs": 72000000,
    "goldFee": 200000,
    "protectionGoldFee": 50000,
    "successRate": 50,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Rope Belt",
        "amount": 25
      },
      {
        "itemName": "Silencer Claws",
        "amount": 25
      },
      {
        "itemName": "Some Grimeleech Wings",
        "amount": 5
      }
    ]
  },
  {
    "id": "basic_vibrancy",
    "name": "Basic Vibrancy",
    "tier": "BASIC",
    "category": "PARALYSIS_DEFLECTION",
    "icon": "/assets/ui/imbuements/swiftness.gif",
    "description": "Removes paralysis with a 15% chance and deflects additional PvP paralysis.",
    "durationMs": 72000000,
    "goldFee": 5000,
    "protectionGoldFee": 10000,
    "successRate": 90,
    "premiumOnly": false,
    "ingredients": [
      {
        "itemName": "Wereboar Hooves",
        "amount": 20
      }
    ]
  },
  {
    "id": "intricate_vibrancy",
    "name": "Intricate Vibrancy",
    "tier": "INTRICATE",
    "category": "PARALYSIS_DEFLECTION",
    "icon": "/assets/ui/imbuements/swiftness.gif",
    "description": "Removes paralysis with a 25% chance and deflects additional PvP paralysis.",
    "durationMs": 72000000,
    "goldFee": 30000,
    "protectionGoldFee": 30000,
    "successRate": 70,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Wereboar Hooves",
        "amount": 20
      },
      {
        "itemName": "Crystallized Anger",
        "amount": 15
      }
    ]
  },
  {
    "id": "powerful_vibrancy",
    "name": "Powerful Vibrancy",
    "tier": "POWERFUL",
    "category": "PARALYSIS_DEFLECTION",
    "icon": "/assets/ui/imbuements/swiftness.gif",
    "description": "Removes paralysis with a 50% chance and deflects additional PvP paralysis.",
    "durationMs": 72000000,
    "goldFee": 200000,
    "protectionGoldFee": 50000,
    "successRate": 50,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Wereboar Hooves",
        "amount": 20
      },
      {
        "itemName": "Crystallized Anger",
        "amount": 15
      },
      {
        "itemName": "Quill",
        "amount": 5
      }
    ]
  },
  {
    "id": "basic_lich_shroud",
    "name": "Basic Lich Shroud",
    "tier": "BASIC",
    "category": "PROTECTION_DEATH",
    "icon": "/assets/ui/imbuements/lich_shroud.gif",
    "description": "Reduces death damage by 2%.",
    "durationMs": 72000000,
    "goldFee": 5000,
    "protectionGoldFee": 10000,
    "successRate": 90,
    "premiumOnly": false,
    "ingredients": [
      {
        "itemName": "Flask Of Embalming Fluid",
        "amount": 25
      }
    ]
  },
  {
    "id": "intricate_lich_shroud",
    "name": "Intricate Lich Shroud",
    "tier": "INTRICATE",
    "category": "PROTECTION_DEATH",
    "icon": "/assets/ui/imbuements/lich_shroud.gif",
    "description": "Reduces death damage by 5%.",
    "durationMs": 72000000,
    "goldFee": 30000,
    "protectionGoldFee": 30000,
    "successRate": 70,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Flask Of Embalming Fluid",
        "amount": 25
      },
      {
        "itemName": "Gloom Wolf Fur",
        "amount": 20
      }
    ]
  },
  {
    "id": "powerful_lich_shroud",
    "name": "Powerful Lich Shroud",
    "tier": "POWERFUL",
    "category": "PROTECTION_DEATH",
    "icon": "/assets/ui/imbuements/lich_shroud.gif",
    "description": "Reduces death damage by 10%.",
    "durationMs": 72000000,
    "goldFee": 200000,
    "protectionGoldFee": 50000,
    "successRate": 50,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Flask Of Embalming Fluid",
        "amount": 25
      },
      {
        "itemName": "Gloom Wolf Fur",
        "amount": 20
      },
      {
        "itemName": "Mystical Hourglass",
        "amount": 5
      }
    ]
  },
  {
    "id": "basic_snake_skin",
    "name": "Basic Snake Skin",
    "tier": "BASIC",
    "category": "PROTECTION_EARTH",
    "icon": "/assets/ui/imbuements/snake_skin.gif",
    "description": "Reduces earth damage by 3%.",
    "durationMs": 72000000,
    "goldFee": 5000,
    "protectionGoldFee": 10000,
    "successRate": 90,
    "premiumOnly": false,
    "ingredients": [
      {
        "itemName": "Piece Of Swampling Wood",
        "amount": 25
      }
    ]
  },
  {
    "id": "intricate_snake_skin",
    "name": "Intricate Snake Skin",
    "tier": "INTRICATE",
    "category": "PROTECTION_EARTH",
    "icon": "/assets/ui/imbuements/snake_skin.gif",
    "description": "Reduces earth damage by 8%.",
    "durationMs": 72000000,
    "goldFee": 30000,
    "protectionGoldFee": 30000,
    "successRate": 70,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Piece Of Swampling Wood",
        "amount": 25
      },
      {
        "itemName": "Snake Skin",
        "amount": 20
      }
    ]
  },
  {
    "id": "powerful_snake_skin",
    "name": "Powerful Snake Skin",
    "tier": "POWERFUL",
    "category": "PROTECTION_EARTH",
    "icon": "/assets/ui/imbuements/snake_skin.gif",
    "description": "Reduces earth damage by 15%.",
    "durationMs": 72000000,
    "goldFee": 200000,
    "protectionGoldFee": 50000,
    "successRate": 50,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Piece Of Swampling Wood",
        "amount": 25
      },
      {
        "itemName": "Snake Skin",
        "amount": 20
      },
      {
        "itemName": "Brimstone Fangs",
        "amount": 10
      }
    ]
  },
  {
    "id": "basic_cloud_fabric",
    "name": "Basic Cloud Fabric",
    "tier": "BASIC",
    "category": "PROTECTION_ENERGY",
    "icon": "/assets/ui/imbuements/cloud_fabric.gif",
    "description": "Reduces energy damage by 3%.",
    "durationMs": 72000000,
    "goldFee": 5000,
    "protectionGoldFee": 10000,
    "successRate": 90,
    "premiumOnly": false,
    "ingredients": [
      {
        "itemName": "Wyvern Talisman",
        "amount": 20
      }
    ]
  },
  {
    "id": "intricate_cloud_fabric",
    "name": "Intricate Cloud Fabric",
    "tier": "INTRICATE",
    "category": "PROTECTION_ENERGY",
    "icon": "/assets/ui/imbuements/cloud_fabric.gif",
    "description": "Reduces energy damage by 8%.",
    "durationMs": 72000000,
    "goldFee": 30000,
    "protectionGoldFee": 30000,
    "successRate": 70,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Wyvern Talisman",
        "amount": 20
      },
      {
        "itemName": "Crawler Head Plating",
        "amount": 15
      }
    ]
  },
  {
    "id": "powerful_cloud_fabric",
    "name": "Powerful Cloud Fabric",
    "tier": "POWERFUL",
    "category": "PROTECTION_ENERGY",
    "icon": "/assets/ui/imbuements/cloud_fabric.gif",
    "description": "Reduces energy damage by 15%.",
    "durationMs": 72000000,
    "goldFee": 200000,
    "protectionGoldFee": 50000,
    "successRate": 50,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Wyvern Talisman",
        "amount": 20
      },
      {
        "itemName": "Crawler Head Plating",
        "amount": 15
      },
      {
        "itemName": "Wyrm Scale",
        "amount": 10
      }
    ]
  },
  {
    "id": "basic_dragon_hide",
    "name": "Basic Dragon Hide",
    "tier": "BASIC",
    "category": "PROTECTION_FIRE",
    "icon": "/assets/ui/imbuements/dragon_hide.gif",
    "description": "Reduces fire damage by 3%.",
    "durationMs": 72000000,
    "goldFee": 5000,
    "protectionGoldFee": 10000,
    "successRate": 90,
    "premiumOnly": false,
    "ingredients": [
      {
        "itemName": "Green Dragon Leather",
        "amount": 20
      }
    ]
  },
  {
    "id": "intricate_dragon_hide",
    "name": "Intricate Dragon Hide",
    "tier": "INTRICATE",
    "category": "PROTECTION_FIRE",
    "icon": "/assets/ui/imbuements/dragon_hide.gif",
    "description": "Reduces fire damage by 8%.",
    "durationMs": 72000000,
    "goldFee": 30000,
    "protectionGoldFee": 30000,
    "successRate": 70,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Green Dragon Leather",
        "amount": 20
      },
      {
        "itemName": "Blazing Bone",
        "amount": 10
      }
    ]
  },
  {
    "id": "powerful_dragon_hide",
    "name": "Powerful Dragon Hide",
    "tier": "POWERFUL",
    "category": "PROTECTION_FIRE",
    "icon": "/assets/ui/imbuements/dragon_hide.gif",
    "description": "Reduces fire damage by 15%.",
    "durationMs": 72000000,
    "goldFee": 200000,
    "protectionGoldFee": 50000,
    "successRate": 50,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Green Dragon Leather",
        "amount": 20
      },
      {
        "itemName": "Blazing Bone",
        "amount": 10
      },
      {
        "itemName": "Draken Sulphur",
        "amount": 5
      }
    ]
  },
  {
    "id": "basic_demon_presence",
    "name": "Basic Demon Presence",
    "tier": "BASIC",
    "category": "PROTECTION_HOLY",
    "icon": "/assets/ui/imbuements/demon_presence.gif",
    "description": "Reduces holy damage by 3%.",
    "durationMs": 72000000,
    "goldFee": 5000,
    "protectionGoldFee": 10000,
    "successRate": 90,
    "premiumOnly": false,
    "ingredients": [
      {
        "itemName": "Cultish Robe",
        "amount": 25
      }
    ]
  },
  {
    "id": "intricate_demon_presence",
    "name": "Intricate Demon Presence",
    "tier": "INTRICATE",
    "category": "PROTECTION_HOLY",
    "icon": "/assets/ui/imbuements/demon_presence.gif",
    "description": "Reduces holy damage by 8%.",
    "durationMs": 72000000,
    "goldFee": 30000,
    "protectionGoldFee": 30000,
    "successRate": 70,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Cultish Robe",
        "amount": 25
      },
      {
        "itemName": "Cultish Mask",
        "amount": 25
      }
    ]
  },
  {
    "id": "powerful_demon_presence",
    "name": "Powerful Demon Presence",
    "tier": "POWERFUL",
    "category": "PROTECTION_HOLY",
    "icon": "/assets/ui/imbuements/demon_presence.gif",
    "description": "Reduces holy damage by 15%.",
    "durationMs": 72000000,
    "goldFee": 200000,
    "protectionGoldFee": 50000,
    "successRate": 50,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Cultish Robe",
        "amount": 25
      },
      {
        "itemName": "Cultish Mask",
        "amount": 25
      },
      {
        "itemName": "Hellspawn Tail",
        "amount": 20
      }
    ]
  },
  {
    "id": "basic_quara_scale",
    "name": "Basic Quara Scale",
    "tier": "BASIC",
    "category": "PROTECTION_ICE",
    "icon": "/assets/ui/imbuements/quara_scale.gif",
    "description": "Reduces ice damage by 3%.",
    "durationMs": 72000000,
    "goldFee": 5000,
    "protectionGoldFee": 10000,
    "successRate": 90,
    "premiumOnly": false,
    "ingredients": [
      {
        "itemName": "Winter Wolf Fur",
        "amount": 25
      }
    ]
  },
  {
    "id": "intricate_quara_scale",
    "name": "Intricate Quara Scale",
    "tier": "INTRICATE",
    "category": "PROTECTION_ICE",
    "icon": "/assets/ui/imbuements/quara_scale.gif",
    "description": "Reduces ice damage by 8%.",
    "durationMs": 72000000,
    "goldFee": 30000,
    "protectionGoldFee": 30000,
    "successRate": 70,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Winter Wolf Fur",
        "amount": 25
      },
      {
        "itemName": "Thick Fur",
        "amount": 15
      }
    ]
  },
  {
    "id": "powerful_quara_scale",
    "name": "Powerful Quara Scale",
    "tier": "POWERFUL",
    "category": "PROTECTION_ICE",
    "icon": "/assets/ui/imbuements/quara_scale.gif",
    "description": "Reduces ice damage by 15%.",
    "durationMs": 72000000,
    "goldFee": 200000,
    "protectionGoldFee": 50000,
    "successRate": 50,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Winter Wolf Fur",
        "amount": 25
      },
      {
        "itemName": "Thick Fur",
        "amount": 15
      },
      {
        "itemName": "Deepling Warts",
        "amount": 10
      }
    ]
  },
  {
    "id": "basic_chop",
    "name": "Basic Chop",
    "tier": "BASIC",
    "category": "SKILL_AXE",
    "icon": "/assets/ui/imbuements/chop.gif",
    "description": "Raises axe fighting by 1.",
    "durationMs": 72000000,
    "goldFee": 5000,
    "protectionGoldFee": 10000,
    "successRate": 90,
    "premiumOnly": false,
    "ingredients": [
      {
        "itemName": "Orc Tooth",
        "amount": 20
      }
    ]
  },
  {
    "id": "intricate_chop",
    "name": "Intricate Chop",
    "tier": "INTRICATE",
    "category": "SKILL_AXE",
    "icon": "/assets/ui/imbuements/chop.gif",
    "description": "Raises axe fighting by 2.",
    "durationMs": 72000000,
    "goldFee": 30000,
    "protectionGoldFee": 30000,
    "successRate": 70,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Orc Tooth",
        "amount": 20
      },
      {
        "itemName": "Battle Stone",
        "amount": 25
      }
    ]
  },
  {
    "id": "powerful_chop",
    "name": "Powerful Chop",
    "tier": "POWERFUL",
    "category": "SKILL_AXE",
    "icon": "/assets/ui/imbuements/chop.gif",
    "description": "Raises axe fighting by 4.",
    "durationMs": 72000000,
    "goldFee": 200000,
    "protectionGoldFee": 50000,
    "successRate": 50,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Orc Tooth",
        "amount": 20
      },
      {
        "itemName": "Battle Stone",
        "amount": 25
      },
      {
        "itemName": "Moohtant Horn",
        "amount": 20
      }
    ]
  },
  {
    "id": "basic_featherweight",
    "name": "Basic Featherweight",
    "tier": "BASIC",
    "category": "SKILL_CAPACITY",
    "icon": "/assets/ui/imbuements/featherweight.gif",
    "description": "Adds 3% capacity.",
    "durationMs": 72000000,
    "goldFee": 5000,
    "protectionGoldFee": 10000,
    "successRate": 90,
    "premiumOnly": false,
    "ingredients": [
      {
        "itemName": "Fairy Wing",
        "amount": 20
      }
    ]
  },
  {
    "id": "intricate_featherweight",
    "name": "Intricate Featherweight",
    "tier": "INTRICATE",
    "category": "SKILL_CAPACITY",
    "icon": "/assets/ui/imbuements/featherweight.gif",
    "description": "Adds 8% capacity.",
    "durationMs": 72000000,
    "goldFee": 30000,
    "protectionGoldFee": 30000,
    "successRate": 70,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Fairy Wing",
        "amount": 20
      },
      {
        "itemName": "Little Bowl Of Myrrh",
        "amount": 10
      }
    ]
  },
  {
    "id": "powerful_featherweight",
    "name": "Powerful Featherweight",
    "tier": "POWERFUL",
    "category": "SKILL_CAPACITY",
    "icon": "/assets/ui/imbuements/featherweight.gif",
    "description": "Adds 15% capacity.",
    "durationMs": 72000000,
    "goldFee": 200000,
    "protectionGoldFee": 50000,
    "successRate": 50,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Fairy Wing",
        "amount": 20
      },
      {
        "itemName": "Little Bowl Of Myrrh",
        "amount": 10
      },
      {
        "itemName": "Goosebump Leather",
        "amount": 5
      }
    ]
  },
  {
    "id": "basic_bash",
    "name": "Basic Bash",
    "tier": "BASIC",
    "category": "SKILL_CLUB",
    "icon": "/assets/ui/imbuements/bash.gif",
    "description": "Raises club fighting by 1.",
    "durationMs": 72000000,
    "goldFee": 5000,
    "protectionGoldFee": 10000,
    "successRate": 90,
    "premiumOnly": false,
    "ingredients": [
      {
        "itemName": "Cyclops Toe",
        "amount": 20
      }
    ]
  },
  {
    "id": "intricate_bash",
    "name": "Intricate Bash",
    "tier": "INTRICATE",
    "category": "SKILL_CLUB",
    "icon": "/assets/ui/imbuements/bash.gif",
    "description": "Raises club fighting by 2.",
    "durationMs": 72000000,
    "goldFee": 30000,
    "protectionGoldFee": 30000,
    "successRate": 70,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Cyclops Toe",
        "amount": 20
      },
      {
        "itemName": "Ogre Nose Ring",
        "amount": 15
      }
    ]
  },
  {
    "id": "powerful_bash",
    "name": "Powerful Bash",
    "tier": "POWERFUL",
    "category": "SKILL_CLUB",
    "icon": "/assets/ui/imbuements/bash.gif",
    "description": "Raises club fighting by 4.",
    "durationMs": 72000000,
    "goldFee": 200000,
    "protectionGoldFee": 50000,
    "successRate": 50,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Cyclops Toe",
        "amount": 20
      },
      {
        "itemName": "Ogre Nose Ring",
        "amount": 15
      },
      {
        "itemName": "Warmaster's Wristguards",
        "amount": 10
      }
    ]
  },
  {
    "id": "basic_precision",
    "name": "Basic Precision",
    "tier": "BASIC",
    "category": "SKILL_DISTANCE",
    "icon": "/assets/ui/imbuements/precision.gif",
    "description": "Raises distance fighting by 1.",
    "durationMs": 72000000,
    "goldFee": 5000,
    "protectionGoldFee": 10000,
    "successRate": 90,
    "premiumOnly": false,
    "ingredients": [
      {
        "itemName": "Elven Scouting Glass",
        "amount": 25
      }
    ]
  },
  {
    "id": "intricate_precision",
    "name": "Intricate Precision",
    "tier": "INTRICATE",
    "category": "SKILL_DISTANCE",
    "icon": "/assets/ui/imbuements/precision.gif",
    "description": "Raises distance fighting by 2.",
    "durationMs": 72000000,
    "goldFee": 30000,
    "protectionGoldFee": 30000,
    "successRate": 70,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Elven Scouting Glass",
        "amount": 25
      },
      {
        "itemName": "Elven Hoof",
        "amount": 20
      }
    ]
  },
  {
    "id": "powerful_precision",
    "name": "Powerful Precision",
    "tier": "POWERFUL",
    "category": "SKILL_DISTANCE",
    "icon": "/assets/ui/imbuements/precision.gif",
    "description": "Raises distance fighting by 4.",
    "durationMs": 72000000,
    "goldFee": 200000,
    "protectionGoldFee": 50000,
    "successRate": 50,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Elven Scouting Glass",
        "amount": 25
      },
      {
        "itemName": "Elven Hoof",
        "amount": 20
      },
      {
        "itemName": "Metal Spike",
        "amount": 10
      }
    ]
  },
  {
    "id": "basic_punch",
    "name": "Basic Punch",
    "tier": "BASIC",
    "category": "SKILL_FIST",
    "icon": "/assets/ui/imbuements/bash.gif",
    "description": "Raises fist fighting by 1.",
    "durationMs": 72000000,
    "goldFee": 5000,
    "protectionGoldFee": 10000,
    "successRate": 90,
    "premiumOnly": false,
    "ingredients": [
      {
        "itemName": "Ghostly Tissue",
        "amount": 20
      }
    ]
  },
  {
    "id": "intricate_punch",
    "name": "Intricate Punch",
    "tier": "INTRICATE",
    "category": "SKILL_FIST",
    "icon": "/assets/ui/imbuements/bash.gif",
    "description": "Raises fist fighting by 2.",
    "durationMs": 72000000,
    "goldFee": 30000,
    "protectionGoldFee": 30000,
    "successRate": 70,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Tarantula Egg",
        "amount": 25
      },
      {
        "itemName": "Mantassin Tail",
        "amount": 20
      }
    ]
  },
  {
    "id": "powerful_punch",
    "name": "Powerful Punch",
    "tier": "POWERFUL",
    "category": "SKILL_FIST",
    "icon": "/assets/ui/imbuements/bash.gif",
    "description": "Raises fist fighting by 4.",
    "durationMs": 72000000,
    "goldFee": 200000,
    "protectionGoldFee": 50000,
    "successRate": 50,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Tarantula Egg",
        "amount": 25
      },
      {
        "itemName": "Mantassin Tail",
        "amount": 20
      },
      {
        "itemName": "Gold-Brocaded Cloth",
        "amount": 15
      }
    ]
  },
  {
    "id": "basic_epiphany",
    "name": "Basic Epiphany",
    "tier": "BASIC",
    "category": "SKILL_MAGIC_LEVEL",
    "icon": "/assets/ui/imbuements/epiphany.gif",
    "description": "Raises magic level by 1.",
    "durationMs": 72000000,
    "goldFee": 5000,
    "protectionGoldFee": 10000,
    "successRate": 90,
    "premiumOnly": false,
    "ingredients": [
      {
        "itemName": "Elvish Talisman",
        "amount": 25
      }
    ]
  },
  {
    "id": "intricate_epiphany",
    "name": "Intricate Epiphany",
    "tier": "INTRICATE",
    "category": "SKILL_MAGIC_LEVEL",
    "icon": "/assets/ui/imbuements/epiphany.gif",
    "description": "Raises magic level by 2.",
    "durationMs": 72000000,
    "goldFee": 30000,
    "protectionGoldFee": 30000,
    "successRate": 70,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Elvish Talisman",
        "amount": 25
      },
      {
        "itemName": "Broken Shamanic Staff",
        "amount": 15
      }
    ]
  },
  {
    "id": "powerful_epiphany",
    "name": "Powerful Epiphany",
    "tier": "POWERFUL",
    "category": "SKILL_MAGIC_LEVEL",
    "icon": "/assets/ui/imbuements/epiphany.gif",
    "description": "Raises magic level by 4.",
    "durationMs": 72000000,
    "goldFee": 200000,
    "protectionGoldFee": 50000,
    "successRate": 50,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Elvish Talisman",
        "amount": 25
      },
      {
        "itemName": "Broken Shamanic Staff",
        "amount": 15
      },
      {
        "itemName": "Strand Of Medusa Hair",
        "amount": 15
      }
    ]
  },
  {
    "id": "basic_blockade",
    "name": "Basic Blockade",
    "tier": "BASIC",
    "category": "SKILL_SHIELDING",
    "icon": "/assets/ui/imbuements/blockade.gif",
    "description": "Raises shielding by 1.",
    "durationMs": 72000000,
    "goldFee": 5000,
    "protectionGoldFee": 10000,
    "successRate": 90,
    "premiumOnly": false,
    "ingredients": [
      {
        "itemName": "Piece Of Scarab Shell",
        "amount": 20
      }
    ]
  },
  {
    "id": "intricate_blockade",
    "name": "Intricate Blockade",
    "tier": "INTRICATE",
    "category": "SKILL_SHIELDING",
    "icon": "/assets/ui/imbuements/blockade.gif",
    "description": "Raises shielding by 2.",
    "durationMs": 72000000,
    "goldFee": 30000,
    "protectionGoldFee": 30000,
    "successRate": 70,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Piece Of Scarab Shell",
        "amount": 20
      },
      {
        "itemName": "Brimstone Shell",
        "amount": 25
      }
    ]
  },
  {
    "id": "powerful_blockade",
    "name": "Powerful Blockade",
    "tier": "POWERFUL",
    "category": "SKILL_SHIELDING",
    "icon": "/assets/ui/imbuements/blockade.gif",
    "description": "Raises shielding by 4.",
    "durationMs": 72000000,
    "goldFee": 200000,
    "protectionGoldFee": 50000,
    "successRate": 50,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Piece Of Scarab Shell",
        "amount": 20
      },
      {
        "itemName": "Brimstone Shell",
        "amount": 25
      },
      {
        "itemName": "Frazzle Skin",
        "amount": 25
      }
    ]
  },
  {
    "id": "basic_swiftness",
    "name": "Basic Swiftness",
    "tier": "BASIC",
    "category": "SKILL_SPEED",
    "icon": "/assets/ui/imbuements/swiftness.gif",
    "description": "Adds 10 movement speed.",
    "durationMs": 72000000,
    "goldFee": 5000,
    "protectionGoldFee": 10000,
    "successRate": 90,
    "premiumOnly": false,
    "ingredients": [
      {
        "itemName": "Damselfly Wing",
        "amount": 15
      }
    ]
  },
  {
    "id": "intricate_swiftness",
    "name": "Intricate Swiftness",
    "tier": "INTRICATE",
    "category": "SKILL_SPEED",
    "icon": "/assets/ui/imbuements/swiftness.gif",
    "description": "Adds 15 movement speed.",
    "durationMs": 72000000,
    "goldFee": 30000,
    "protectionGoldFee": 30000,
    "successRate": 70,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Damselfly Wing",
        "amount": 15
      },
      {
        "itemName": "Compass",
        "amount": 25
      }
    ]
  },
  {
    "id": "powerful_swiftness",
    "name": "Powerful Swiftness",
    "tier": "POWERFUL",
    "category": "SKILL_SPEED",
    "icon": "/assets/ui/imbuements/swiftness.gif",
    "description": "Adds 30 movement speed.",
    "durationMs": 72000000,
    "goldFee": 200000,
    "protectionGoldFee": 50000,
    "successRate": 50,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Damselfly Wing",
        "amount": 15
      },
      {
        "itemName": "Compass",
        "amount": 25
      },
      {
        "itemName": "Waspoid Wing",
        "amount": 20
      }
    ]
  },
  {
    "id": "basic_slash",
    "name": "Basic Slash",
    "tier": "BASIC",
    "category": "SKILL_SWORD",
    "icon": "/assets/ui/imbuements/slash.gif",
    "description": "Raises sword fighting by 1.",
    "durationMs": 72000000,
    "goldFee": 5000,
    "protectionGoldFee": 10000,
    "successRate": 90,
    "premiumOnly": false,
    "ingredients": [
      {
        "itemName": "Lion's Mane",
        "amount": 25
      }
    ]
  },
  {
    "id": "intricate_slash",
    "name": "Intricate Slash",
    "tier": "INTRICATE",
    "category": "SKILL_SWORD",
    "icon": "/assets/ui/imbuements/slash.gif",
    "description": "Raises sword fighting by 2.",
    "durationMs": 72000000,
    "goldFee": 30000,
    "protectionGoldFee": 30000,
    "successRate": 70,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Lion's Mane",
        "amount": 25
      },
      {
        "itemName": "Mooh'tah Shell",
        "amount": 25
      }
    ]
  },
  {
    "id": "powerful_slash",
    "name": "Powerful Slash",
    "tier": "POWERFUL",
    "category": "SKILL_SWORD",
    "icon": "/assets/ui/imbuements/slash.gif",
    "description": "Raises sword fighting by 4.",
    "durationMs": 72000000,
    "goldFee": 200000,
    "protectionGoldFee": 50000,
    "successRate": 50,
    "premiumOnly": true,
    "ingredients": [
      {
        "itemName": "Lion's Mane",
        "amount": 25
      },
      {
        "itemName": "Mooh'tah Shell",
        "amount": 25
      },
      {
        "itemName": "War Crystal",
        "amount": 5
      }
    ]
  }
];
